linters:
    PropertySortOrder:
      order:
        -
      ignore_unspecified: true
    Indentation:
        width: 4
    SelectorDepth:
        max_depth: 9
    NestingDepth:
        max_depth: 9
    SpaceAfterPropertyColon:
      style: one_space_or_newline
