version: "2"
checks:
  complex-logic:
    enabled: true
    config:
        threshold: 4
  file-lines:
    enabled: true
    config:
        threshold: 500
  method-complexity:
    enabled: true
    config:
        threshold: 5
  method-count:
    enabled: true
    config:
        threshold: 20
  method-lines:
    enabled: true
    config:
        threshold: 100
  nested-control-flow:
    enabled: true
    config:
        threshold: 4
  return-statements:
    enabled: true
    config:
        threshold: 5
  argument-count:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    checks:
      complexity:
        enabled: false
    config:
      config: frontend/.eslintrc
  pep8:
    enabled: true
    checks:
      complexity:
        enabled: false
  scss-lint:
    enabled: true
    config: frontend/.scss-lint.yml

exclude_patterns:
- "backend/*/migrations/*"
- "backend/*/tests/*"
- "backend/*/wsgi.py"
- "backend/manage.py"
- "frontend/config/"
- "frontend/scripts/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.test.js"
