engines:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: frontend/.eslintrc
  pep8:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript: 
      - python: 
ratings:
  paths:
  - "**.py"
  - "**.js"
  - "**.scss"
exclude_paths:
- backend/*/migrations/*
- backend/*/tests/*
- backend/*/wsgi.py
- backend/manage.py
- frontend/config/
- frontend/scripts/
