sudo: required

language: python

python:
- '3.4'

services:
    - docker

before_install:
    - docker-compose build

before_script:
    - docker-compose up

script:
    - docker-compose exec web /code/run_tests.sh

notifications:
  slack:
    rooms:
        - secure:

env:
  global:
      - secure:
