sudo: required

language: python

python:
- '3.4'

services:
    - docker

before_install:
    - sudo apt-get install jq
    - sudo pip install --upgrade awscli
    - sudo pip install --upgrade awsebcli

    - ./deploy/scripts/travis_decrypt.sh

    - git clone https://github.com/toggle-corp/react-store.git frontend/src/vendor/react-store
    - mkdir -p frontend/src/vendor
    - git clone https://github.com/toggle-corp/ravl.git frontend/src/vendor/ravl
    - env > .env
    - docker-compose build

before_script:
    - docker-compose up -d

script:
    - docker-compose exec web /code/scripts/run_tests.sh

after_success:
    - ./deploy/scripts/travis_deploy.sh ;

notifications:
  slack:
    rooms:
        - secure: "V74yUcOmhjKMCyvX5DxZrdOEfkJmzwlB4jqUXCLHYI9maIj8wQGjgXTKjANHgHg4jJheStGXmjTN6cIpk4WLN5YS3DeaKpdpotrUp3m2BV+nt5cPEpjdeQVo5Biii+JY7D/0aiRre15BlT4m0GhrIaR1Gqto5LUNS1sRoF05nn0B8MnhFczcVdk3XipfRgeyvzZ7oWTaFnWN1TQXaqMesJYoBE2Jg0j6Jis6fZO2Mwuk2nxLzm4KptlLCZHPPXLmqwEybmRo/amK7BE0i3NeLp+25UtVImILDjc3jGhA+IH0yhrUF3Cy2rYKqA7MjDJBTFIsLMvIaZ5QjEyr9JCE2b4suOpkvKl4+l+oY0TrM67z1c4/AZK84KyPzNOzdJhv7IeBbRP7j8KgzZvYx7Lq9uyIZAji6yFY53bIFVYn+LztHKb1WYfj6yTC3eLVkdEHk8JtCLixn7I1k32wlreiUCwZ45JfL6ZKIiiF2rVbEVEDd2GE8Bx2SS6bKABLkr2HZEeqf9Xl0G5Xd98hXZ2wtPPmaRSRgmXwQJfe2kFflRgrW3qFmBka7p7oHMH2KJugScLW+ApZSkOfVneX4MpD3ttDGc7e4c7GpNAgXEhO4pvp+dsL3ADcokLqzjuRIxvMydcW4KqDKuNr44bs/IQhPNzt71iPKOTmuFJxNxk+BIA="
