sudo: required

language: python

python:
- '3.4'

services:
    - docker

before_install:
    - sudo apt-get install jq
    - sudo pip install --upgrade awscli
    - sudo pip install --upgrade awsebcli

    - ./deploy/scripts/travis_decrypt.sh

    - mkdir -p frontend/src/vendor

    - git clone https://github.com/toggle-corp/react-store.git frontend/src/vendor/react-store
    - git --git-dir=frontend/src/vendor/react-store/.git --no-pager show --pretty=fuller --quiet
    - cp frontend/src/vendor/react-store/stylesheets/_user-imports-sample.scss frontend/src/vendor/react-store/stylesheets/_user-imports.scss

    - git clone https://github.com/toggle-corp/ravl.git frontend/src/vendor/ravl
    - git --git-dir=frontend/src/vendor/ravl/.git --no-pager show --pretty=fuller --quiet

    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter

    - env > .env
    - docker-compose build

before_script:
    - docker-compose up -d
    - ./cc-test-reporter before-build

script:
    - docker-compose exec web /code/scripts/run_tests.sh
    - cd frontend ; ../cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -p frontend/ ; cd ..
    - cd backend ; ../cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -p backend/ ; cd ..

after_success:
    - ./deploy/scripts/travis_deploy.sh ;

notifications:
  slack:
    rooms:
        - secure: "V74yUcOmhjKMCyvX5DxZrdOEfkJmzwlB4jqUXCLHYI9maIj8wQGjgXTKjANHgHg4jJheStGXmjTN6cIpk4WLN5YS3DeaKpdpotrUp3m2BV+nt5cPEpjdeQVo5Biii+JY7D/0aiRre15BlT4m0GhrIaR1Gqto5LUNS1sRoF05nn0B8MnhFczcVdk3XipfRgeyvzZ7oWTaFnWN1TQXaqMesJYoBE2Jg0j6Jis6fZO2Mwuk2nxLzm4KptlLCZHPPXLmqwEybmRo/amK7BE0i3NeLp+25UtVImILDjc3jGhA+IH0yhrUF3Cy2rYKqA7MjDJBTFIsLMvIaZ5QjEyr9JCE2b4suOpkvKl4+l+oY0TrM67z1c4/AZK84KyPzNOzdJhv7IeBbRP7j8KgzZvYx7Lq9uyIZAji6yFY53bIFVYn+LztHKb1WYfj6yTC3eLVkdEHk8JtCLixn7I1k32wlreiUCwZ45JfL6ZKIiiF2rVbEVEDd2GE8Bx2SS6bKABLkr2HZEeqf9Xl0G5Xd98hXZ2wtPPmaRSRgmXwQJfe2kFflRgrW3qFmBka7p7oHMH2KJugScLW+ApZSkOfVneX4MpD3ttDGc7e4c7GpNAgXEhO4pvp+dsL3ADcokLqzjuRIxvMydcW4KqDKuNr44bs/IQhPNzt71iPKOTmuFJxNxk+BIA="

env:
  global:
    - secure: "DUY5KdEPr6oz8pPDCwEotHwMmomJ1BTOaEjIQ7/+y+w6u3icfXosuSCjyitp16jzFydt7/DjfBZImAAShiH36FeNbft25ftRYQMdjyM9EyB9cYbUfgl6GgOrPPYbsdNT04G9GlZEMp3dY+CTDrDBPraaqHKRcs3Jiwjmbl4MwKl7jgOI9oZpH9elDjiAT3giWvs+iwvZf4+kC+4/x85LCJ6ZCvOUEVnVJkbHedFTEx07G7nVkFs8TZnwEXTAX4ccKoAWIqUXbBEYhPcor4lHoVFYv8RN4Njepil2Ed83OXDvqMXzwogBAj4M6jbs2Tcu+KHcbdOdfLyu3O/obHpbTsGwlAiMcTTtM4M1dFmcp7dUpTgi07Ze5pFuqbHYDdovmINhBn/c9iheMOUwSmTFVMrsHNk5c5FSDInFaQv77TBpzQXa+jCGY0LZdBNiLR7mqSM/pt17MvkzCqCw95Xe6aURB4TORwH+mUDYC9R4k4AduRGyPm+gCOTqmOMMno8tiIyAozO4NRGBcHWITM8Q9kwYJXhFlRkCo/4lhOQnKHVeFeDuay0LjI1pMnfm/HNFC0fQopf7+JT36aBxpyaCsZaW3i4bk/XD03ZHPZtzo7YGjlONmMS/lIh3bHnIbeIYrbglf9xHf7Tr+WdTH6BuMkei2NxVeigK0lQQPRBa3y0="
