version: '3'

services:
    db:
        image: devtc/deep-postgres:0.1
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    redis:
        image: redis:latest
        volumes:
            - ./redis-data:/data
    web:
        build: .
        env_file:
            - .env
        command: ['/code/scripts/wait-for-it.sh', 'db:5432', '--', '/code/scripts/run_develop.sh', 'django']
        volumes:
            - .:/code
            - ./media:/media
        ports:
            - '8000:8000'
        depends_on:
            - db
            - redis
    react:
        build: .
        env_file:
            - .env
        command: ['/code/scripts/run_develop.sh', 'react']
        volumes:
            - .:/code
            - ./media:/media
        ports:
            - '3000:3000'
        depends_on:
            - db
            - redis
