version: '3'

services:
    channel: # Django Channel
        build: .
        env_file:
            - .env-cern
        environment:
          - WORKER_TYPE=channel
        command: ['/code/deploy/scripts/eb_exec.sh']
        ports:
            - '8000:80'

    celery:
        build: .
        env_file:
            - .env-cern
        environment:
          - WORKER_TYPE=celery
        command: ['/code/deploy/scripts/eb_exec.sh']
