version: '3'

services:
    db:
        image: postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    redis:
        image: redis:latest
        volumes:
            - ./redis-data:/data
    nginx:
        build: ./deploy/nginx/
        ports:
            - '80:80'
        depends_on:
            - web
        volumes:
            - static-volume:/static
            - media-volume:/media
            - socket-volume:/socket
    web:
        build: .
        command: ['./wait-for-it.sh', 'db:5432', '--', '/code/run_production.sh']
        volumes:
            - static-volume:/static
            - media-volume:/media
            - socket-volume:/socket
        env_file:
            - production.env
        depends_on:
            - db
            - redis

volumes:
    static-volume:
    media-volume:
    socket-volume:
