const initialDevLangState = {
    strings: {
        1: 'Owner',
        2: 'Created',
        3: 'Published',
        5: 'Publisher',
        6: 'Assignee',
        7: 'Confidentiality',
        8: 'Status',
        9: 'Search',
        10: 'Apply Filter',
        11: 'Clear Filter',
        12: 'Add Leads',
        13: 'Title',
        14: 'Any',
        15: 'Entries',
        16: 'Actions',
        17: 'Anybody',
        18: 'Anytime',
        20: 'Text',
        21: 'Type',
        22: 'Prev',
        23: 'Next',
        25: 'Save',
        28: 'We cannot currently preview this publisher. Please open it in a new tab or copy the URL.',
        30: 'Invalid URL',
        31: 'Project',
        32: 'URL',
        33: 'Website',
        34: 'Add New Source From:',
        35: 'Drive',
        36: 'Dropbox',
        37: 'Local Disk',
        38: 'Select One',
        39: 'eg: Nepal Monitoring',
        40: 'eg: Lead 12:21:00 PM',
        41: 'eg: https://deeper.togglecorp.com',
        43: 'eg: Newspaper',
        44: 'eg: 12/12/2012',
        45: 'Enter text description here',
        47: 'Clear Similar Filter',
        48: 'Source Preview',
        49: 'Gathering website information for preview',
        51: 'Countries',
        52: 'Search Country',
        53: 'Add New Country',
        54: 'Delete Country',
        55: 'Are you sure you want to remove country',
        56: 'General',
        57: 'Key Figures',
        58: 'Population Data',
        59: 'Seasonal Calendar',
        60: 'Media Sources',
        61: 'Cancel',
        62: 'Save Changes',
        63: 'Human Development Index',
        64: 'UNDER FIVE MORTALITY RATE (per 1.000 live births)',
        65: 'UPROOTED PEOPLE (refugees + IDPs + returned refugees)',
        66: 'Inform Score',
        67: 'Index',
        68: 'Geo-Rank',
        69: 'Geo-Score',
        70: 'Rank',
        71: 'U5M',
        72: 'Number of Refugees',
        73: 'Percentage of Uprooted People',
        74: 'Number of IDPs',
        75: 'Number of returned refugees',
        76: 'Risk Class',
        77: 'Inform Risk Index',
        78: 'Hazard and Exposure',
        79: 'Vulnerability',
        80: 'Lack of Coping Capacity',
        81: 'Total Population',
        82: 'Enter Population',
        83: 'Source',
        84: 'Enter Source',
        87: 'Add Admin Level',
        88: 'Are you sure you want to remove admin level {adminLevel}?',
        89: 'Admin Level',
        90: 'Add Level Name',
        91: 'Country',
        92: 'Name Property',
        93: 'NAME_ENGL',
        94: 'Pcode Property',
        95: 'NAME_PCODE',
        96: 'Parent name property',
        97: 'NAME_ENFG',
        98: 'Parent pcode property',
        99: 'NAME_PPCODE',
        100: 'Parent Admin Level',
        101: 'Country Code',
        102: 'NPL',
        103: 'Name',
        104: 'Nepal',
        105: 'WB Region',
        106: 'Enter WB Region',
        107: 'WB Income Region',
        108: 'Enter WB Income Region',
        109: 'OCHA Region',
        110: 'Enter OCHA Region',
        111: 'ECHO Region',
        112: 'Enter ECHO Region',
        113: 'UN Geographical Region',
        114: 'Enter UN Geographical Region',
        115: 'UN Geographical Sub Region',
        116: 'Enter UN Geographical Sub Region',
        117: 'There are no countries.',
        118: 'Select a country to view its detail.',
        119: 'Selected county is not found.',
        120: 'Level',
        121: 'Admin Level Name',
        123: 'Admin Levels',
        125: 'Load GEO Shape File',
        129: 'Extract lead information from URL',
        130: 'Apply this value to all elements.',
        131: 'Apply this value to all elements below.',
        132: 'Preview Not Available',
        133: 'Are you sure you want to discard this lead?',
        134: 'Are you sure you want to delete this assessment?',
        135: 'Search Similar Lead',
        136: 'Edit lead',
        137: 'Remove lead',
        138: 'Add entry from this lead',
        139: 'Add subcategory',
        140: 'This lead type is unrecognized.',
        141: 'Are you sure you want to remove this lead? The lead along with all the associated entries and assessment will be removed.',
        142: 'Tabular',
        143: 'Add assessment from this lead',
        144: 'No assessment template found for this project.',
        150: 'First Name',
        151: 'eg: John',
        152: 'Last Name',
        153: 'eg: Doe',
        154: 'Organization',
        155: 'eg: ToggleCorp',
        158: 'Edit Profile',
        160: 'Rights',
        161: 'Joined At',
        163: 'Created At',
        164: 'Last Modified At',
        166: 'Members',
        167: 'View User Group',
        168: 'Edit User Group',
        169: 'Delete User Group',
        170: 'View Project',
        171: 'Edit Project',
        172: 'Delete Project',
        173: 'Projects',
        174: 'Add Project',
        175: 'Groups',
        176: 'Add User Group',
        177: 'Failed to add members.',
        178: 'eg: ACAPS',
        179: 'Create',
        180: 'Project Title',
        181: 'Enter Project Name',
        184: 'Email',
        185: 'Start Date',
        187: 'View Member',
        188: 'Revoke Admin Rights',
        189: 'Grant Admin Rights',
        190: 'Delete Member',
        191: 'Delete Lead',
        192: 'Add Member',
        193: 'Are you sure you want to delete the project {title}?',
        194: 'Are you sure you want to delete the usergroup {title}?',
        195: 'Are you sure you want to revoke admin rights form {memberName}?',
        196: 'Are you sure your want to grant admin rights to {memberName}?',
        197: 'Are you sure you want to remove the member {memberName}?',
        198: 'User Group Not Found',
        199: 'User Not Found',
        200: 'Description',
        201: 'User Group',
        202: 'Activity Log',
        203: 'Profile Image Missing',
        204: 'Failed to save user group.',
        205: 'Region Remove',
        206: 'Region removed successfully.',
        207: 'Cannot remove region.',
        208: 'Cannot remove region. Please check your network connection and try again',
        209: 'Show lead preview',
        301: 'Add',
        302: 'Search Project',
        303: 'Add New Project',
        304: 'Select a project to view its details',
        305: 'You do not have enough permissions to edit this project.',
        319: 'Are you sure you want to remove {title} from project {projectTitle}?',
        323: 'Update',
        324: 'Revert',
        331: 'Enter Project Description',
        333: 'Enter Project Start Date',
        334: 'End Date',
        335: 'Enter Project End Date',
        336: 'Regions',
        337: 'Select regions',
        338: 'User Groups',
        339: 'Select user groups',
        341: 'Search Regions',
        342: 'Add Region',
        343: 'There are no regions in this project.',
        344: 'Create new region',
        345: 'Use existing regions',
        346: 'Region Title',
        347: 'eg: Nepal',
        348: 'Code',
        349: 'eg: NPL',
        350: 'ID',
        351: 'Remove Region',
        352: 'Clone & Edit',
        354: 'Are you sure you want to clone {title}?',
        357: 'Search Analysis Framework',
        358: 'Add New Analysis Framework',
        359: 'There are no analysis frameworks.',
        360: 'Saved',
        361: 'eg: ACAPS framework',
        362: 'Use',
        363: 'Edit',
        365: 'Are you sure you want to use {title}?',
        366: 'If you use this analysis framework, you will recieve updates when the owner updates it.',
        369: 'eg: ACAPS Category Editor',
        370: 'Search Category Editor',
        371: 'Add New Category Editor',
        372: 'There are no category editors.',
        373: 'If you use this category editor, you will recieve updates when the owner updates it.',
        374: 'After cloning and editing this category editor, you will not recieve any updates made by owner.',
        377: 'General Details',
        378: 'Region details',
        379: 'Analysis Framework',
        380: 'Category Editor',
        401: 'Category',
        402: 'Select Category',
        403: 'Add Category',
        404: 'Edit Category',
        405: 'Delete Category',
        406: 'Nothing Here',
        408: 'eg: Sector, Affected Groups, etc.',
        410: 'Ok',
        411: 'eg: Wash',
        413: 'eg: Wash stands for Water, Sanitation and Hygiene',
        414: 'Add new Sub-Category',
        415: 'Add New Word',
        416: 'Word',
        417: 'eg: people affected',
        418: 'Sub-Category Details',
        419: 'Remove',
        420: 'Number of Words:',
        421: 'No words yet',
        422: 'Add Word Manually',
        423: 'Document',
        424: 'Simplified',
        425: 'Extracted Words',
        426: 'Select From Gallery',
        427: 'Apply',
        428: 'Are you sure you want to delete category {category}?',
        429: 'Are you sure you want to delete subcategory {subcategory}?',
        500: 'Server Error',
        501: 'Failed connecting to server',
        502: 'NLP',
        504: 'It\'s accurate',
        505: 'It\'s not accurate',
        506: 'Show suggestions for :',
        508: 'Entities',
        509: 'Go to Overview',
        511: 'Go to List',
        512: 'Entry',
        514: 'Excerpt',
        515: 'Format excerpt',
        517: 'Assisted',
        518: 'Original',
        519: 'Images',
        521: 'Select an excerpt',
        522: 'Add Entry',
        523: 'Mark current entry for removal',
        525: 'Unmark current entry for removal',
        528: 'Clear',
        530: 'Edit Entry',
        531: 'Set',
        533: 'Select geo region',
        534: 'Couldn\'t load geo filter options',
        535: 'Select locations',
        537: 'Search Excerpt',
        538: 'Created By',
        540: 'NER',
        541: 'Assited tagging feedback',
        542: 'Thank you for your feedback.',
        543: 'Oops! It seems you don\'t have any entries. Please go back to the overview page to add some entries.',
        545: 'Locations',
        600: 'Export',
        601: 'Show Preview',
        602: 'Start Export',
        603: 'DOCX',
        604: 'PDF',
        605: 'XLXS',
        606: 'JSON',
        609: 'Entry Attributes',
        610: 'Lead Attributes',
        620: 'View all exports',
        621: 'User Exports',
        622: 'Unable to load your previous exports.',
        623: 'Doc. type',
        624: 'Exported At',
        627: 'Export Type',
        628: 'Download',
        629: 'Pending',
        630: 'Error',
        631: 'Completed',
        632: 'Recent Exports',
        633: 'Go back to exports',
        634: 'Decoupled Entries',
        635: 'Note that by selecting this option, it can greatly increase the amount of time to generate the export.',
        636: 'Disaggregate data for any list values (i.e. multiple administrative areas or multiple select fields).',
        637: 'Your export has been started.\nPlease go to view all exports page for further information on export.',
        638: 'You don\'t have any matrices in your analysis framework.',
        639: 'Report Structure',
        640: 'No export options available',
        641: 'Leads',
        642: 'Couldn\'t load leads',
        643: 'Select',
        644: 'Unselect',
        646: 'Couldn\'t load project',
        648: 'Couldn\'t load analysis framework',
        704: 'Date',
        706: 'Text or Image Excerpt',
        709: 'Geo Location',
        713: 'Geo Area',
        718: 'Matrix 1D',
        719: 'Add / edit cell',
        720: 'Add Cell',
        721: 'Edit row',
        722: 'Add row',
        723: 'Matrix 2D',
        724: 'Dimension-Y',
        726: 'Dimension-X',
        733: 'Tooltip',
        737: 'Multiselect',
        738: 'Option',
        739: 'eg: Context',
        740: 'Edit Multiselect',
        741: 'Add Option',
        742: 'Number Matrix',
        744: 'eg: Row',
        745: 'eg: Its a tooltip',
        746: 'eg: Column',
        747: 'Edit number matrix',
        748: 'Rows',
        749: 'Add Row Unit',
        750: 'Columns',
        751: 'Add Column Unit',
        752: 'Number',
        753: 'Organigram',
        754: 'Organ',
        755: 'Edit Organigram',
        757: 'Scale',
        758: 'eg: Reliable',
        759: 'Edit Scales',
        760: 'Add Scale Unit',
        763: 'eg: Overview',
        764: 'Color',
        766: 'Add Child',
        767: 'Remove Element',
        768: 'eg: 999 999',
        773: 'Edit Title',
        775: 'Options',
        777: 'Information date',
        778: 'Exit',
        779: 'Default?',
        780: 'List',
        781: 'Overview',
        782: 'Untitled dimension',
        786: 'Subdimensions',
        788: 'Add subdimension',
        789: 'Add dimension',
        792: 'Edit Matrix-2d',
        803: 'Welcome to DEEP (BETA)',
        805: 'Login with HID',
        806: 'Or',
        808: 'Password',
        809: 'Forgot Password?',
        810: 'Do not have an account yet?',
        811: 'Register',
        812: 'Check your inbox: {email}',
        813: 'john.doe@mail.com',
        814: 'Login',
        817: 'Go back to login',
        818: 'Thank You for signing up, Please check your email <{email}> to set your password.',
        819: 'John',
        821: 'Doe',
        823: 'Togglecorp',
        825: 'Already have an account?',
        826: 'Submit',
        870: 'Error 404',
        871: 'Oops! You have come too DEEP',
        872: 'This is where the DEEP Kraken rests',
        873: 'Go to DEEP',
        875: 'Welcome to the',
        876: 'DEEP',
        877: 'Seems like you do not have any projects yet.',
        878: 'To get started, create a project from your profile.',
        879: 'Go to your profile',
        900: 'User Profile Edit',
        901: 'User Edit Successful',
        902: 'User Edit Failure.',
        903: 'User Edit Failure. Please check your network connection and try again',
        904: 'User Group Delete',
        905: 'User Group Successfully Deleted',
        906: 'User Group Deletion Failure',
        907: 'User Group Deletion Failure. Please check your network connection and try again',
        908: 'User Group Add',
        909: 'User Group Successfully Created',
        910: 'User Group Creation Failure',
        911: 'User Group Creation Failure. Please check your network connection and try again',
        912: 'User Project Delete',
        913: 'Project Successfully Deleted',
        914: 'Project Deletion Failure',
        915: 'Project Deletion Failure. Please check your network connection and try again',
        916: 'User Project Add',
        917: 'Project Successfully Created',
        918: 'Project Creation Failure',
        919: 'Project Creation Failure. Please check your network connection and try again',
        920: 'Add User Membership ',
        921: 'User Added Successfully ',
        924: 'Remove User Membership',
        925: 'User Removed Successfully ',
        926: 'Cannot remove user',
        927: 'Cannot remove user. Please check your network connection and try again',
        928: 'Membership Role',
        929: 'User role successfully updated',
        930: 'User role update failure.',
        931: 'Cannot update user role. Please check your network connection and try again',
        932: 'User Group Edit',
        933: 'Name Updated Successfully',
        937: 'Country Delete Successful',
        938: 'Cannot delete country.',
        939: 'Cannot delete country. Please check your network connection and try again',
        940: 'Add Country',
        941: 'Country Added Successfully',
        942: 'Cannot add country.',
        943: 'Cannot add country. Please check your network connection and try again',
        948: 'Delete Admin Level',
        949: 'Admin Level Successfully Deleted',
        950: 'Cannot delete admin level.',
        951: 'Cannot delete admin level. Please check your network connection and try again',
        953: 'Admin Level Successfully Added',
        954: 'Cannot add admin level.',
        955: 'Cannot add admin level. Please check your network connection and try again',
        956: 'Edit Admin Level',
        957: 'Admin Level Successfully Updated',
        960: 'Project Details',
        961: 'Project Details Successfully Updated',
        962: 'Cannot update project details.',
        963: 'Cannot update project details. Please check your network connection and try again',
        965: 'Analysis Framework Successfully Added ',
        966: 'Cannot add Analysis Framework.',
        967: 'Cannot add Analysis Framework. Please check your network connection and try again',
        968: 'Analysis Framework Form',
        969: 'Analysis Framework Form Updated',
        970: 'Cannot update Analysis Framework Form.',
        971: 'Cannot update Analysis Framework Form. Please check your network connection and try again',
        972: 'Save Lead',
        973: 'Lead Save Successful',
        974: '{errorCount} lead(s) could not be saved.',
        977: 'Lead Successfully Deleted',
        978: 'Lead File Not Found',
        979: 'Lead Delete failed. Please check your network connection and try again',
        981: 'Analysis Framework was updated in server.',
        982: 'Your copy was overridden by server\'s copy',
        983: 'Successfully saved the framework.',
        984: 'Category editor was updated in server.',
        985: 'Invalid drop source',
        986: 'Drag and Drop are only valid from Extracted Words.',
        987: 'Some entries were updated in server.',
        988: 'Save Entry',
        989: 'Entries Successfully Saved',
        990: '{errorCount} entries could not be saved.',
        993: 'Lead Successfully Removed',
        994: 'Remove Leads',
        995: 'Leads Successfully Removed',
        996: 'Region details were updated in server.',
        997: 'Region details Successfully Saved.',
        998: 'Save Region',
        999: 'There was an error while fetching existing users',
        1200: 'User',
        1206: 'Search Gallery Files',
        1209: 'Loading File',
        1210: 'Open Dropbox chooser',
        1211: 'Open Google chooser',
        1214: 'Map Not Available',
        1217: 'Anon',
        1219: 'Select Event',
        1220: 'Admin Panel',
        1221: 'Logout',
        1222: 'Locating the required gigapixels to render ...',
        1223: 'Programming the flux capacitor ...',
        1224: 'Shovelling coal into the server ...',
        1225: 'Spinning up the hamster ...',
        1226: 'Checking the gravitational constant in your locale ...',
        1227: 'The server is powered by a lemon and two electrodes ...',
        1228: 'Don\'t think of purple hippos ...',
        1229: 'Dividing eternity by zero, please be patient...',
        1230: 'Photographing cats... Attaching signs... MEME complete ...',
        1231: 'Nobody exists on purpose, nobody belongs anywhere ...',
        1232: 'Swapping time and space...',
        1233: 'Greetings Earthling! ...',
        1234: 'I am Mr. Meeseeks! Look at me ...',
        1235: 'Oh, yeaah! You gotta get schwifty. ...',
        1236: 'Shhhh! The Kraken is sleeping ...',
        1237: 'BETA',
        1300: 'Are you sure you want to leave? You may lose your unsaved changes.',
        1301: 'Oops! File Not Found',
        1302: 'Upload file',
        1928: 'Fail to update users list, Please check your network connection and try again',
        2000: 'Browser Extension',
        2001: 'Your extension has been successfully set up.',
        2002: 'An error occured while setting up the extension. Please make sure you have installed and enabled the extension.',
        2003: 'Do you want to apply this value to all leads?',
        2004: 'Do you want to apply this value to all leads below?',
        2005: 'Do you want to apply this value to all entries?',
        2006: 'Do you want to apply this value to all entries below?',
        2007: 'Discard',
        2008: 'No GEO file uploaded.',
        2009: 'GEO File',
        5551: 'Selected',
        5552: 'All',
        5553: 'Filtered',
        5556: 'Invalid file(s) selected.',
        5557: 'File Selection',
        5558: 'Password Reset',
        5559: 'Home',
        5560: 'Dashboard',
        5561: 'Leads Visualization',
        5562: 'Assessments',
        5563: 'Edit Assessment',
        5566: 'User Profile',
        5569: 'Weekly Snapshot',
        5570: 'Api Docs',
        5571: '404',
        5572: 'String Management',
        6000: 'Do you want to remove this widget?',
        7001: 'Metadata',
        7002: 'Methodology',
        7003: 'Summary',
        7004: 'Score',
        7036: 'Response Schema',
        7037: 'Request Schema',
        7038: 'Loading Api',
        7039: 'Subsectors',
        7040: 'Untitled Row',
        7041: 'No row selected',
        7042: 'Project members',
        7500: 'Couldn\'t upload image',
        7501: 'Couldn\'t upload file',
        8101: 'Delete this Assessment',
        8102: 'Edit this Assessment',
        8501: 'Select a source to add new lead',
        1003: 'Failed to save region detail.',
        1004: 'Please wait while we process the text for this lead. It can take some time depending on the size of the lead.',
        251: 'DEEP supports .json, .geojson and shapefiles compressed in .zip',
        801: 'Show Visualization',
        802: 'Mark as pending',
        804: 'Mark as processed',
        1999: 'Leads per page',
        7000: 'Do you want to mark the lead as pending?',
        8001: 'Do you want to mark the lead as processed?',
        8002: 'Are you sure you want to continue?',
        253: 'Under Construction',

        1005: 'Edit entries',
        9000: 'Priority issue',
        9001: 'Affected location',
        9002: 'Population with limited access',
        9003: 'Population with restricted access',
        9004: 'Population with humanitarian access constraints',
        9005: 'Priority sector',
        9006: 'Affected group',
        9007: 'Specific need group',
        9008: 'Population in moderate need of assistance (not life threatening) (do not know)',
        9009: 'Population in severe need of assistance (life threatening) (do not know)',
        9010: 'Population in need of assistance (do not know)',
        9011: '1',
        9012: '2',
        9013: '3',
        9014: 'Population in moderate need of assistance (not life threatening)',
        9015: 'Population in severe need of assistance (life threatening)',
        9016: 'Population in need of assistance',
        9017: 'Select at least 3 sectors in Methodology',
        9018: 'Cross sector',
        9019: 'Humanitarian access',

        9020: 'Basic information',
        9021: 'Additional documents',
        9022: 'Executive summary',
        9023: 'Assessment database',
        9024: 'Questionnaire',

        9025: 'Focuses',
        9026: 'Sectors',
        9027: 'Affected groups',
        9028: 'Locations',
        9029: 'Methodology content',

        9030: 'Objectives',
        9031: 'Data collection techniques',
        9032: 'Sampling',
        9033: 'Limitations',
        9034: 'Attributes',

        9035: 'Drag and drop objectives here',
        9036: 'Drag and drop data collection techniques here',
        9037: 'Drag and drop sampling (site and respondent selection) here',
        9038: 'Drag and drop limitations here',
        9919: 'Select',

        1100: 'Connectors',
        1101: 'Search Connectors',
        1102: 'Add Connector',
        1103: 'Gotham Daily',
        1104: 'Source Type',
        1105: 'RSS Feed',
        1106: 'Connector Create',
        1107: 'Connector was successfully created.',
        1109: 'Connector Sources',
        1110: 'There was a problem while fetching connector sources.',
        1111: 'Select a connector to view its detail.',
        1112: 'There was a problem while fetching connector.',
        1113: 'Connectors',
        1114: 'The connector you are looking for does not exist.',
        1115: 'There are no connectors.',
        1116: 'Failed to patch connector.',
        1117: 'Connector details were saved successfully.',
        1118: 'Failed to create connector.',
        1119: 'Users',
        1120: 'Visibility',
        1121: 'Set it to local',
        1122: 'Set it to global',
        1123: 'You need project admin rights to change this setting.',
        1124: 'Remove project',
        1125: 'Failed to fetch projects',
        1126: 'Failed to save project.',
        1127: 'Failed to create new category editor.',
        1128: 'Failed to create new framework.',
        1129: 'Lead Group',
        1130: 'Progress reports of June',
        1131: 'Add Lead Group',
    },
    links: {
        af: {
            analysisFramework: 379,
            headerList: 780,
            headerOverview: 781,
            gotoListButtonLabel: 511,
            saveButtonLabel: 25,
            cancelButtonLabel: 61,
            gotoOverviewButtonLabel: 509,
            dateWidgetLabel: 704,
            excerptWidgetLabel: 514,
            textOrImageExcerptWidgetLabel: 706,
            geoWidgetLabel: 709,
            geoAreaButtonLabel: 713,
            matrix1DWidgetLabel: 718,
            matrix1DModalTitle: 719,
            addCellButtonLabel: 720,
            editRowModalTitle: 721,
            addRowButtonLabel: 722,
            titlePlaceholderOverview: 763,
            matrix2DWidgetLabel: 723,
            dimensionXLabel: 726,
            dimensionYLabel: 724,
            untitledDimensionTitle: 782,
            untitledRowTitle: 7040,
            noRowSelected: 7041,
            tooltipTitle: 733,
            multiselectWidgetLabel: 737,
            optionLabel: 738,
            optionPlaceholder: 739,
            editMultiselectModalTitle: 740,
            addOptionButtonLabel: 741,
            numberMatrixWidgetLabel: 742,
            titleLabel: 13,
            titlePlaceholderRow: 744,
            tooltipPlaceholder: 745,
            titlePlaceholderColumn: 746,
            editNumberMatrixModalTitle: 747,
            rowsLabel: 748,
            addRowUnitButtonLabel: 749,
            columnsLabel: 750,
            addColumnUnitButtonLabel: 751,
            numberWidgetLabel: 752,
            organigramWidgetLabel: 753,
            organPlaceholder: 754,
            editOrganigramModaltitle: 755,
            applyButtonLabel: 427,
            scaleWidgetLabel: 757,
            titlePlaceholderScale: 758,
            editScaleModalTitle: 759,
            addscaleUnitButtonLabel: 760,
            altEntryLabel: 512,
            colorLabel: 764,
            addChildButtonTitle: 766,
            removeElementButtonTitle: 767,
            numberPlaceholder: 768,
            editTitleModalHeader: 773,
            widgetTitlePlaceholder: 13,
            optionsHeader: 775,
            informationDateCheckboxLabel: 777,
            exitButtonLabel: 778,
            defaultButtonLabel: 779,
            title: 13,
            tooltip: 733,
            color: 764,
            subdimensions: 786,
            addSubdimensionButtonTitle: 788,
            addDimensionButtonTitle: 789,
            saveButtonTitle: 25,
            cancelButtonTitle: 61,
            editModalTitle: 792,
            empty: 406,
            confirmDeletewWidget: 6000,
            subsectorsLabel: 7039,
            formatExcerpt: 515,
        },
        api: {
            loadingLabel: 7038,
            responseSchemaLabel: 7036,
            requestSchemaLabel: 7037,
        },
        ary: {
            metadataTabLabel: 7001,
            methodologyTabLabel: 7002,
            summaryTabLabel: 7003,
            scoreTabLabel: 7004,
            noAryTemplateForProject: 144,
            editEntriesText: 1005,
        },
        ce: {
            saveCeButtonLabel: 25,
            headerCategoryLabel: 401,
            selectCategoryPlaceholder: 402,
            addCategoryTooltip: 403,
            editCategoryTooltip: 404,
            deleteCategoryTooltip: 405,
            nothingHereText: 406,
            addCategoryTitleLabel: 13,
            addCategoryTitlePlaceholder: 408,
            modalCancel: 61,
            modalOk: 410,
            addNewSubCategoryModalTitle: 414,
            addSubCategoryTitleLabel: 13,
            addSubCategoryTitlePlaceholder: 411,
            addSubCategoryDescriptionLabel: 200,
            addSubCategoryDescriptionPlaceholder: 413,
            addNewWordModalTitle: 415,
            addNewWordLabel: 416,
            addNewWordPlaceholder: 417,
            subCategoryDetailsText: 418,
            removeCategoryButtonLabel: 419,
            subCategoryTitleLabel: 13,
            subCategoryTitlePlaceholder: 408,
            subCategoryDescriptionLabel: 200,
            subCategoryDescriptionPlaceholder: 413,
            numberOfWordsLabel: 420,
            noWordsText: 421,
            addWordManuallyButtonLabel: 422,
            documentTabLabel: 423,
            simplifiedTabLabel: 424,
            ngramsTabLabel: 425,
            selectFromGalleryButtonLabel: 426,
            applyButtonLabel: 427,
            titleLabel: 13,
            confirmTextDeleteCategory: 428,
            confirmTextDeleteSubCategory: 429,
            exitButtonLabel: 778,
            addSubcategory: 139,
        },
        common: {
            select: 643,
            unselect: 644,
            altUser: 1200,
            underConstructionLabel: 253,
            tableHeaderSelect: 643,
            tableHeaderType: 21,
            tableHeaderName: 103,
            tableHeaderDateCreated: 2,
            searchGalleryLabel: 9,
            searchGalleryPlaceholder: 1206,
            cancelButtonLabel: 61,
            addButtonLabel: 301,
            loadingFileLabel: 1209,
            uploadFileButtonLabel: 1302,
            openDropboxChooserText: 1210,
            openGoogleChooserText: 1211,
            serverErrorText: 500,
            connectionFailureText: 501,
            mapNotAvailable: 1214,
            previewNotAvailable: 132,
            anonymousLabel: 1217,
            deepLabel: 876,
            selectEventPlaceholder: 1219,
            adminPanelLabel: 1220,
            logoutLabel: 1221,
            loadingMessages1: 1222,
            loadingMessages2: 1223,
            loadingMessages3: 1224,
            loadingMessages4: 1225,
            loadingMessages5: 1226,
            loadingMessages6: 1227,
            loadingMessages7: 1228,
            loadingMessages8: 1229,
            loadingMessages9: 1230,
            loadingMessages10: 1231,
            loadingMessages11: 1232,
            loadingMessages12: 1233,
            loadingMessages13: 1234,
            loadingMessages14: 1235,
            loadingMessages15: 1236,
            betaLabel: 1237,
            youHaveUnsavedChanges: 1300,
            deepFileNotFound: 1301,
            simplifyingLead: 1004,
        },
        countries: {
            countriesLabel: 51,
            noFileUploadedLabel: 2008,
            geoFileLabel: 2009,
            searchCountryPlaceholer: 52,
            addCountryButtonLabel: 301,
            addCountryModalHeaderLabel: 53,
            deleteCountryButtonLabel: 54,
            deleteCountryConfirm: 55,
            generalTabLabel: 56,
            keyFiguesTabLabel: 57,
            populationTabLabel: 58,
            seasonalTabLabel: 59,
            mediaTabLabel: 60,
            cancelButtonLabel: 61,
            saveChangesButtonLabel: 62,
            saveButtonLabel: 25,
            discardButtonLabel: 2007,
            humanDevelopmentIndexLabel: 63,
            underFiveMortalityLabel: 64,
            uprootedPeopleLabel: 65,
            informScoreLabel: 66,
            indexLabel: 67,
            geoRankLabel: 68,
            geoScoreLabel: 69,
            rankLabel: 70,
            u5mLabel: 71,
            numberOfRefugeesLabel: 72,
            percentageUprootedPeopleLabel: 73,
            numberIdpLabel: 74,
            numberReturnedRefugeesLabel: 75,
            riskClassLabel: 76,
            informRiskIndexLabel: 77,
            hazardAndExposureLabel: 78,
            vulnerabilityLabel: 79,
            lackOfCopingCapacityLabel: 80,
            totalPopulationLabel: 81,
            totalPopulationPlaceholder: 82,
            sourceLabel: 83,
            sourcePlaceholder: 84,
            addAdminLevelButtonLabel: 87,
            removeAdminLevelConfirm: 88,
            adminLevelLabel: 89,
            adminLevelPlaceholder: 89,
            adminLevelNameLabel: 90,
            adminLevelNamePlaceholder: 91,
            namePropertyLabel: 92,
            namePropertyPlaceholder: 93,
            pcodePropertyLabel: 94,
            pcodePropertyPlaceholder: 95,
            parentNamePropLabel: 96,
            parentNamePropPlaceholder: 97,
            parentCodePropLabel: 98,
            parentCodePropPlaceholder: 99,
            parentAdminLevelLabel: 100,
            parentAdminLevelPlaceholder: 99,
            countryCodeLabel: 101,
            countryCodePlaceholder: 102,
            countryNameLabel: 103,
            countryNamePlaceholder: 104,
            wbRegionLabel: 105,
            wbRegionPlaceholer: 106,
            wbIncomeRegionLabel: 107,
            wbIncomeRegionPlaceholder: 108,
            ochaRegionLabel: 109,
            ochaRegionPlaceholder: 110,
            echoRegionLabel: 111,
            echoRegionPlaceholder: 112,
            unGeoRegionLabel: 113,
            unGeoRegionPlaceholer: 114,
            unGeoSubregionLabel: 115,
            unGeoSubregionPlaceholer: 116,
            noCountriesText: 117,
            selectCountryText: 118,
            countryNotFoundText: 119,
            levelLabel: 120,
            adminLevelNameText: 121,
            actionsLabel: 16,
            adminLevelsHeader: 123,
            editAdminLevelModalTitle: 956,
            loadGeoShapeFile: 125,
            regionGeneralInfoLabel: 378,
            addRegionButtonLabel: 301,
            regionPatchErrorText: 1003,
            geoshapeTooltip: 251,
        },
        entry: {
            sourceText: 83,
            serverErrorText: 500,
            connectionFailureText: 501,
            sourceNLP: 502,
            sourceCE: 380,
            accurateTextTitle: 504,
            notAccurateTextTitle: 505,
            showSuggestionText: 506,
            addEntryButtonLabel: 301,
            nlpLabel: 502,
            entitiesLabel: 508,
            ceLabel: 380,
            gotoOverviewButtonLabel: 509,
            saveButtonLabel: 25,
            gotoListButtonLabel: 511,
            altLabel: 512,
            previewNotAvailableText: 132,
            simplifiedTabLabel: 424,
            assistedTabLabel: 517,
            originalTabLabel: 518,
            tabularTabLabel: 142,
            imagesTabLabel: 519,
            entriesTabLabel: 15,
            unrecognizedLeadMessage: 140,
            selectExcerptPlaceholder: 521,
            addEntryButtonTitle: 522,
            removeEntryButtonTitle: 523,
            undoRemoveEntryButtonTitle: 525,
            applyFilterButtonLabel: 427,
            clearFilterButtonLabel: 528,
            editEntryLinkTitle: 363,
            editEntryButtonLabel: 530,
            setGeoSelectionButtonLabel: 531,
            cancelGeoSelectionButtonLabel: 61,
            regionSelectPlaceholder: 533,
            geoOptionsFatalMessage: 534,
            locationSelectPlaceholder: 535,
            searchFilterLabel: 9,
            searchFilterPlaceholder: 537,
            createdByFilterLabel: 538,
            createdAtFilterLabel: 163,
            sourceNER: 540,
            assitedTaggingFeedbackTitle: 541,
            assitedTaggingFeedbackMessage: 542,
            noEntryFound: 543,
            regionSelectTitle: 336,
            locationSelectTitle: 545,
            applyAllButtonTitle: 130,
            applyAllBelowButtonTitle: 131,
            applyToAll: 2005,
            applyToAllBelow: 2006,
        },
        export: {
            headerExport: 600,
            showPreviewButtonLabel: 601,
            startExportButtonLabel: 602,
            viewAllExportsButtonLabel: 620,
            docxLabel: 603,
            pdfLabel: 604,
            xlxsLabel: 605,
            jsonLabel: 606,
            entryAttributesLabel: 609,
            leadAttributesLabel: 610,
            createdAtLabel: 163,
            previewNotAvailableLabel: 132,
            serverErrorText: 500,
            connectionFailureText: 501,
            userExportsTitle: 621,
            userExportsFataMessage: 622,
            documentTypeHeaderLabel: 623,
            exportedAtHeaderLabel: 624,
            exportTitleHeaderLabel: 13,
            statusHeaderLabel: 8,
            exportTypeHeaderLabel: 627,
            exportDownloadHeaderLabel: 628,
            pendingStatusLabel: 629,
            errorStatusLabel: 630,
            completedStatusLabel: 631,
            userExportsHeader: 632,
            goBackToExportLabel: 633,
            decoupledEntriesLabel: 634,
            decoupledEntriesTitle: 635,
            decoupledEntriesTitle2: 636,
            exportStartedNotifyMessage: 637,
            noMatrixAfText: 638,
            noOptionsAvailable: 640,
            reportStructureLabel: 639,
            leadsLabel: 641,
            cantLoadLeads: 642,
            selectLabel: 643,
            titleLabel: 13,
            projectLabel: 31,
            cantLoadProject: 646,
            afLabel: 379,
            cantLoadAf: 648,
        },
        fourHundredFour: {
            errorFourHundredFour: 870,
            message1: 871,
            message2: 872,
            goToDeep: 873,
        },
        homescreen: {
            welcomeText: 875,
            deepLabel: 876,
            message1: 877,
            message2: 878,
            goToProfile: 879,
        },
        arys: {
            titleLabel: 13,
            createdAt: 163,
            tableHeaderActions: 16,
            aryDeleteConfirmText: 134,
            placeholderAnybody: 17,
            placeholderAnytime: 18,
            placeholderSearch: 9,
            filterDateCreated: 2,
            createdByFilterLabel: 538,
            filterApplyFilter: 10,
            filterClearFilter: 11,
            removeAryButtonTitle: 8101,
            editAryButtonTitle: 8102,
        },
        assessmentMetadata: {
            basicInformationTitle: 9020,
            additionalDocumentsTitle: 9021,
            executiveSummaryTitle: 9022,
            assessmentDatabaseTitle: 9023,
            questionnaireTitle: 9024,
        },
        assessmentMethodology: {
            focusesTitle: 9025,
            sectorsTitle: 9026,
            affectedGroupsTitle: 9027,
            locationsTitle: 9028,
            methodologyContentTitle: 9029,
            attributesTitle: 9034,
            objectivesTitle: 9030,
            dataCollectionTechniquesTitle: 9031,
            samplingTitle: 9032,
            limitationsTitle: 9033,

            objectivesPlaceholder: 9035,
            dataCollectionTechniquesPlaceholder: 9036,
            samplingPlaceholder: 9037,
            limitationsPlaceholder: 9038,
        },
        assessmentSummary: {
            priorityIssue: 9000,
            affectedLocation: 9001,
            limitedAccessPopulation: 9002,
            restrictedAccessPopulation: 9003,
            humanitarianAccessPopulation: 9004,
            prioritySector: 9005,
            affectedGroup: 9006,
            specificNeedGroup: 9007,
            moderateAssistancePopulationUnknown: 9008,
            severeAssistancePopulationUnknown: 9009,
            assistancePopulationUnknown: 9010,
            rank1Title: 9011,
            rank2Title: 9012,
            rank3Title: 9013,
            moderateAssistancePopulation: 9014,
            severeAssistancePopulation: 9015,
            assistancePopulation: 9016,
            crossSectorEmptyText: 9017,
            crossSectorTitle: 9018,
            humanitarianAccessTitle: 9019,
        },
        leads: {
            assigneeLabel: 6,
            assignee: 6,
            filterClearFilter: 11,
            filterSourceType: 21,
            filterStatus: 8,
            leads: 641,
            placeholderAny: 14,
            placeholderSearch: 9,
            cannotPreviewUrl: 28,
            filterDateCreated: 2,
            filterDatePublished: 3,
            filterConfidentiality: 7,
            filterApplyFilter: 10,
            filterClearSimilarFilter: 47,
            placeholderAnybody: 17,
            placeholderAnytime: 18,
            tableHeaderOwner: 1,
            tableHeaderDateCreated: 2,
            tableHeaderDatePublished: 3,
            tableHeaderConfidentiality: 7,
            tableHeaderPublisher: 5,
            tableHeaderNoOfEntries: 15,
            tableHeaderStatus: 8,
            tableHeaderActions: 16,
            addSourcesButtonLabel: 12,
            invalidUrl: 30,
            gatheringWebsiteInfoLabel: 49,
            searchSimilarLeadButtonTitle: 135,
            editLeadButtonTitle: 136,
            removeLeadLeadButtonTitle: 137,
            addEntryFromLeadButtonTitle: 138,
            addAssessmentFromLeadButtonTitle: 143,
            leadDeleteConfirmText: 141,
            leadDeleteSuccess: 977,
            leadDeleteFailure: 979,
            leadDelete: 191,
            showViz: 801,
            markAsPendingTitle: 802,
            markAsProcessedTitle: 804,
            leadsPerPage: 1999,
            titleLabel: 13,
            leadConfirmText: 8002,
            leadMarkPendingConfirmText: 7000,
            leadMarkProcessedConfirmText: 8001,
        },
        addLeads: {
            noConnectorsLabel: 1115,
            modalCancelLabel: 61,
            modalAddLabel: 301,
            addLeadGroupTitleLabel: 13,
            addLeadGroupTitlePlaceholder: 1130,
            addLeadGroupModalTitle: 1131,
            modalSelectLabel: 9919,
            fileUploadFailText: 7501,
            filterPublisher: 5,
            previousButtonLabel: 22,
            nextButtonLabel: 23,
            saveCurrentButtonTitle: 5551,
            saveAllButtonTitle: 5552,
            saveAllFilteredButtonTitle: 5553,
            removeCurrentButtonTitle: 5551,
            removeAllButtonTitle: 5552,
            removeAllFilteredButtonTitle: 5553,
            saveButtonTitle: 25,
            removeButtonTitle: 419,
            googleDriveLabel: 35,
            dropboxLabel: 36,
            localDiskLabel: 37,
            textLabel: 20,
            connectorsLabel: 1100,
            selectLabel: 643,
            titleLabel: 13,
            datePublishedLabel: 3,
            projectLabel: 31,
            publisherLabel: 5,
            confidentialityLabel: 7,
            leadGroupLabel: 1129,
            assigneeLabel: 6,
            urlLabel: 32,
            websiteLabel: 33,
            selectInputPlaceholderLabel: 38,
            projectPlaceholderLabel: 39,
            titlePlaceHolderLabel: 40,
            urlPlaceholderLabel: 41,
            publisherPlaceHolderLabel: 43,
            datePublishedPlaceholderLabel: 44,
            textareaPlaceholderLabel: 45,
            sourcePreview: 48,
            applyAllButtonTitle: 130,
            applyAllBelowButtonTitle: 131,
            previewNotAvailable: 132,
            deleteLeadConfirmText: 133,
            leadFileNotFound: 978,
            extractLead: 129,
            applyToAll: 2003,
            applyToAllBelow: 2004,
            removeAllCompletedButtonTitle: 360,
            noLeadsText: 8501,
            searchConnectorPlaceholder: 1101,
            showLeadPreviewLabel: 209,
            addSourceFromLabel: 34,
            filterClearFilter: 11,
            filterSourceType: 21,
            filterStatus: 8,
            placeholderAny: 14,
            placeholderSearch: 9,
        },
        login: {
            welcomeToText: 803,
            logInWIthHid: 805,
            orText: 806,
            emailLabel: 184,
            passwordLabel: 808,
            forgotPasswordText: 809,
            noAccountYetText: 810,
            checkInboxText: 812,
            emailPlaceholder: 813,
            loginLabel: 814,
            registerLabel: 811,
            goBackToLoginText: 817,
            checkYourEmailText: 818,
            firstNameLabel: 150,
            firstNamePlaceholder: 819,
            lastNameLabel: 152,
            lastNamePlaceholder: 821,
            organizationLabel: 154,
            organizationPlaceholder: 823,
            alreadyHaveAccountText: 825,
            submitForgetPassword: 826,
        },
        notification: {
            connectorTitle: 1113,
            connectorGetFailure: 1112,
            connectorCreateTitle: 1106,
            connectorCreateSuccess: 1107,
            connectorSourcesTitle: 1109,
            connectorPatchSuccess: 1117,
            connectorSourcesGetFailure: 1110,
            connectorUpdateOverriden: 982,
            usersTitle: 1119,
            usersListGetFailure: 999,
            userProfileEdit: 900,
            userEditSuccess: 901,
            userEditFailure: 902,
            userEditFatal: 903,
            usersPullFailure: 1928,
            userEditImageUploadFailure: 7500,
            userGroupDelete: 904,
            userGroupDeleteSuccess: 905,
            userGroupDeleteFailure: 906,
            userGroupDeleteFatal: 907,
            userGroupCreate: 908,
            userGroupCreateSuccess: 909,
            userGroupCreateFailure: 910,
            userGroupCreateFatal: 911,
            userProjectDelete: 912,
            userProjectDeleteSuccess: 913,
            userProjectDeleteFailure: 914,
            userProjectDeleteFatal: 915,
            userProjectCreate: 916,
            userProjectCreateSuccess: 917,
            userProjectCreateFailure: 918,
            userProjectCreateFatal: 919,
            userMembershipCreate: 920,
            userMembershipCreateSuccess: 921,
            userMembershipDelete: 924,
            userMembershipDeleteSuccess: 925,
            userMembershipDeleteFailure: 926,
            userMembershipDeleteFatal: 927,
            userMembershipRole: 928,
            userMembershipRoleSuccess: 929,
            userMembershipRoleFailure: 930,
            userMembershipRoleFatal: 931,
            userGroupEdit: 932,
            userGroupEditSuccess: 933,
            countryDelete: 54,
            countryDeleteSuccess: 937,
            countryDeleteFailure: 938,
            countryDeleteFatal: 939,
            regionRemove: 205,
            regionRemoveSuccess: 206,
            regionRemoveFailure: 207,
            regionRemoveFatal: 208,
            countryCreate: 940,
            countryCreateSuccess: 941,
            countryCreateFailure: 942,
            countryCreateFatal: 943,
            adminLevelDelete: 948,
            adminLevelDeleteSuccess: 949,
            adminLevelDeleteFailure: 950,
            adminLevelDeleteFatal: 951,
            adminLevelCreate: 87,
            adminLevelCreateSuccess: 953,
            adminLevelCreateFailure: 954,
            adminLevelCreateFatal: 955,
            adminLevelEdit: 956,
            adminLevelEditSuccess: 957,
            projectsTitle: 31,
            projectsGetFailure: 1125,
            projectDetails: 960,
            projectDetailsSuccess: 961,
            projectDetailsFailure: 962,
            projectDetailsFatal: 963,
            afCreate: 379,
            afCreateSuccess: 965,
            afCreateFailure: 966,
            afCreateFatal: 967,
            afFormEdit: 968,
            afFormEditSuccess: 969,
            afFormEditFailure: 970,
            afFormEditFatal: 971,
            leadSave: 972,
            leadSaveSuccess: 973,
            leadSaveFailure: 974,
            leadDiscard: 137,
            leadDiscardSuccess: 993,
            leadsDiscard: 994,
            leadsDiscardSuccess: 995,
            afTitle: 379,
            afUpdate: 981,
            afUpdateOverridden: 982,
            afSaveSuccess: 983,
            ceUpdate: 984,
            ceUpdateOverridden: 982,
            invalidDropSource: 985,
            validDropAlert: 986,
            entryUpdate: 987,
            regionUpdate: 996,
            entryUpdateOverridden: 982,
            regionUpdateOverridden: 982,
            browserExtensionSuccessTitle: 2000,
            browserExtensionSuccessMessage: 2001,
            browserExtensionFailureTitle: 2000,
            browserExtensionFailureMessage: 2002,
            entrySave: 988,
            entrySaveSuccess: 989,
            entrySaveFailure: 990,
            regionSaveSuccess: 997,
            regionSave: 998,
            invalidFileSelection: 5556,
            fileSelection: 5557,
        },
        pageTitle: {
            login: 814,
            register: 811,
            passwordReset: 5558,

            homeScreen: 5559,
            dashboard: 5560,

            leads: 641,
            leadsViz: 5561,
            addLeads: 12,
            entries: 15,
            arys: 5562,
            editAry: 5563,
            export: 600,

            editEntries: 1005,

            userProfile: 5566,
            userGroup: 201,
            adminPanel: 1220,
            countries: 51,
            projects: 173,
            connectors: 1100,

            analysisFramework: 379,

            categoryEditor: 380,

            weeklySnapshot: 5569,

            apiDocs: 5570,
            userExports: 621,

            fourHundredFour: 5571,

            browserExtension: 2000,
            stringManagement: 5572,
        },
        project: {
            projectSaveFailure: 1126,
            categoryEditorCreateFailure: 1127,
            frameworkCreateFailure: 1128,
            headerProjects: 173,
            addProjectButtonLabel: 301,
            searchProjectPlaceholder: 302,
            addProjectModalTitle: 303,
            noProjectText: 304,
            forbiddenText: 305,
            tableHeaderName: 103,
            tableHeaderEmail: 184,
            tableHeaderRights: 160,
            tableHeaderJoinedAt: 161,
            tableHeaderActions: 16,
            deleteMemberLinkTitle: 190,
            revokeAdminRightsTitle: 188,
            grantAdminRightsTitle: 189,
            modalCancel: 61,
            modalUpdate: 323,
            modalRevert: 324,
            modalSave: 25,
            discardButtonLabel: 2007,
            modalAdd: 301,
            projectNameLabel: 103,
            projectNamePlaceholder: 39,
            projectDescriptionLabel: 200,
            projectDescriptionPlaceholder: 331,
            projectStartDateLabel: 185,
            projectStartDatePlaceholder: 333,
            projectEndDateLabel: 334,
            projectEndDatePlaceholder: 335,
            projectRegionLabel: 336,
            projectRegionPlaceholder: 337,
            projectUserGroupLabel: 338,
            projectUserGroupPlaceholder: 339,
            projectMembersLabel: 7042,
            addRegionButtonLabel: 301,
            searchRegionPlaceholder: 341,
            addRegionModalTitle: 342,
            noRegionText: 343,
            createNewRegionText: 344,
            useExistingRegionText: 345,
            addRegionTitleLabel: 346,
            addRegionTitlePlaceholder: 347,
            addRegionCodeLabel: 348,
            addRegionCodePlaceholder: 349,
            tableHeaderId: 350,
            removeRegionButtonLabel: 351,
            cloneEditButtonLabel: 352,
            confirmRemoveText: 319,
            confirmCloneText: 354,
            addAfButtonLabel: 301,
            searchAfPlaceholder: 357,
            addAfModalTitle: 358,
            noAfText: 359,
            addAfTitleLabel: 13,
            addAfTitlePlaceholder: 361,
            useAfButtonLabel: 362,
            editAfButtonLabel: 363,
            cloneEditAfButtonLabel: 352,
            confirmUseAf: 365,
            confirmUseAfText: 366,
            confirmCloneAf: 354,
            addCeTitleLabel: 13,
            addCeTitlePlaceholder: 369,
            useCeButtonLabel: 362,
            editCeButtonLabel: 363,
            cloneEditCeButtonLabel: 352,
            addCeButtonLabel: 301,
            searchCePlaceholder: 370,
            addCeModalTitle: 371,
            noCeText: 372,
            confirmUseCe: 365,
            confirmUseCeText: 373,
            confirmCloneCe: 354,
            confirmCloneCeText: 374,
            generalDetailsLabel: 377,
            regionsLabel: 336,
            analysisFrameworkLabel: 379,
            categoryEditorLabel: 380,
            regionLabel: 336,
            saveButtonLabel: 25,
        },
        connector: {
            noConnectorsLabel: 1115,
            headerConnectors: 1100,
            addConnectorButtonLabel: 301,
            searchConnectorPlaceholder: 1101,
            addConnectorModalTitle: 1102,
            addConnectorModalTitleLabel: 13,
            addConnectorModalTitlePlaceholder: 1103,
            addConnectorModalSourceLabel: 1104,
            addConnectorModalSourcePlaceholder: 1105,
            revokeAdminRightsTitle: 188,
            deleteMemberLinkTitle: 190,
            grantAdminRightsTitle: 189,
            noConnectorSelectedTitle: 1111,
            connectorPatchFailure: 1116,
            connectorCreateFailure: 1118,
            connectorUsersLabel: 1119,
            connectorProjectsLabel: 173,
            connectorDetailSaveLabel: 25,
            connectorDetailCancelLabel: 61,
            connectorTitleLabel: 13,
            noConnectorFoundLabel: 1114,
            tableHeaderTitle: 13,
            tableHeaderVisibility: 1120,
            setLocalVisibilityTitle: 1121,
            setGlobalVisibilityTitle: 1122,
            needAdminRightsTitle: 1123,
            removeProjectTitle: 1124,
            tableHeaderName: 103,
            tableHeaderEmail: 184,
            tableHeaderRights: 160,
            tableHeaderJoinedAt: 161,
            tableHeaderActions: 16,
            modalCancel: 61,
            modalCreate: 179,
        },
        user: {
            firstNameLabel: 150,
            firstNamePlaceholder: 151,
            lastNameLabel: 152,
            lastNamePlaceholder: 153,
            organizationLabel: 154,
            organizationPlaceholder: 155,
            modalSave: 25,
            modalCancel: 61,
            modalCreate: 179,
            editProfileModalHeader: 158,
            tableHeaderTitle: 13,
            tableHeaderRights: 160,
            tableHeaderJoinedAt: 161,
            tableHeaderActions: 16,
            tableHeaderCreatedAt: 163,
            tableHeaderLastModifiedAt: 164,
            tableHeaderStatus: 8,
            tableHeaderMembers: 166,
            tableHeaderName: 103,
            tableHeaderEmail: 184,
            tableHeaderStartDate: 185,
            tableHeaderCountries: 51,
            viewUsergroupLinkTitle: 167,
            editUsergroupLinkTitle: 168,
            deleteUsergroupLinkTitle: 169,
            viewProjectLinkTitle: 170,
            editProjectLinkTitle: 171,
            deleteProjectLinkTitle: 172,
            headerProjects: 173,
            addProjectButtonLabel: 174,
            headerGroups: 175,
            addUserGroupButtonLabel: 176,
            addUserGroupModalLabel: 13,
            addUserGroupModalPlaceholder: 178,
            addProjectModalLabel: 180,
            addProjectModalPlaceholder: 181,
            userGroupEditModalLabel: 168,
            userGroupModalDescriptionLabel: 200,
            userGroupPatchFatal: 204,
            viewMemberLinkTitle: 187,
            revokeAdminLinkTitle: 188,
            grantAdminLinkTitle: 189,
            deleteMemberLinkTitle: 190,
            addMemberErrorText: 177,
            placeholderSearch: 9,
            addMemberButtonLabel: 192,
            confirmTextDeleteUserGroup: 194,
            confirmTextDeleteProject: 193,
            confirmTextRevokeAdmin: 195,
            confirmTextGrantAdmin: 196,
            confirmTextRemoveMember: 197,
            userGroupNotFound: 198,
            userNotFound: 199,
            userGroupTitle: 201,
            userGroupActivtyLogTitle: 202,
            userImageNotFound: 203,
        },
    },
};
export default initialDevLangState;
