const initialLangState = {
    selectedLanguage: 'np',
    fallbackLanguage: undefined,
    languages: {
        np: {
            strings: {
                150: 'नाम',
                152: 'थर',
                154: 'संगठन',
                184: 'इमेल',
                803: 'डीप(बेटा)मा स्वागत छ ',
                805: 'एच.आइ.डी.बाट प्रवेश गर्',
                806: 'अथवा',
                808: 'गुप्तसब्ध',
                809: 'म भुलक्कड हुँ। गुप्तसब्ध थाहाछैन।',
                810: 'खाता छैन?',
                811: 'दर्ता गर्',
                812: 'आफ्नो इमेल जाँच गर्: {email}',
                813: 'राम.अधिकारी@टोगल.कम',
                814: 'प्रवेश गर्',
                817: 'प्रवेशमा फर्की',
                818: 'दर्ताको लागि धन्यवाद। पासवर्ड निर्धारित गर्न आफ्नो इमेल {email} जाँच गर्',
                819: 'राम',
                821: 'अधिकारी',
                823: 'टोगल',
                825: 'पहिले नै खाता छ?',
                826: 'पेश गर्',
            },
            links: {
                login: {
                    welcomeToText: 803,
                    logInWIthHid: 805,
                    orText: 806,
                    emailLabel: 184,
                    passwordLabel: 808,
                    forgotPasswordText: 809,
                    noAccountYetText: 810,
                    checkInboxText: 812,
                    emailPlaceholder: 813,
                    loginLabel: 814,
                    registerLabel: 811,
                    goBackToLoginText: 817,
                    checkYourEmailText: 818,
                    firstNameLabel: 150,
                    firstNamePlaceholder: 819,
                    lastNameLabel: 152,
                    lastNamePlaceholder: 821,
                    organizationLabel: 154,
                    organizationPlaceholder: 823,
                    alreadyHaveAccountText: 825,
                    submitForgetPassword: 826,
                },
            },
        },
    },
};
export default initialLangState;
