const initialLangState = {
    selectedLanguage: 'en',
    languages: {
        en: {
            strings: {
                1: 'Owner',
                2: 'Date Created',
                3: 'Date Published',
                5: 'Publisher',
                6: 'Assignee',
                7: 'Confidentiality',
                8: 'Status',
                9: 'Search',
                10: 'Apply Filter',
                11: 'Clear Filter',
                12: 'Add Leads',
                13: 'Title',
                14: 'Any',
                15: 'Entries',
                16: 'Actions',
                17: 'Anybody',
                18: 'Anytime',
                20: 'Text',
                21: 'Type',
                22: 'Prev',
                23: 'Next',
                25: 'Save',
                28: 'Oops! For some reason DEEP can’t preview this publisher. Please open it in a new tab or copy the URL above:',
                30: 'Invalid URL',
                31: 'Project',
                32: 'URL',
                33: 'Website',
                34: 'Add New Source From:',
                35: 'Drive',
                36: 'Dropbox',
                37: 'Local Disk',
                38: 'Select One',
                39: 'eg: Nepal Monitoring',
                40: 'eg: Lead 12:21:00 PM',
                41: 'eg: https://deeper.togglecorp.com',
                43: 'eg: Newspaper',
                44: 'eg: 12/12/2012',
                45: 'Enter text description here',
                47: 'Clear Similar Filter',
                48: 'Source Preview',
                49: 'Gathering Website Information to Preview',
                51: 'Countries',
                52: 'Search Country',
                54: 'Delete Country',
                55: 'Are you sure you want to remove country',
                56: 'General',
                57: 'Key Figures',
                58: 'Population Data',
                59: 'Seasonal Calendar',
                60: 'Media Sources',
                61: 'Cancel',
                62: 'Save Changes',
                63: 'Human Development Index',
                64: 'UNDER FIVE MORTALITY RATE (per 1.000 live births)',
                65: 'UPROOTED PEOPLE (refugees + IDPs + returned refugees)',
                66: 'Inform Score',
                67: 'Index',
                68: 'Geo-Rank',
                69: 'Geo-Score',
                70: 'Rank',
                71: 'U5M',
                72: 'Number of Refugees',
                73: 'Percentage of Uprooted People',
                74: 'Number of IDPs',
                75: 'Number of returned refugees',
                76: 'Risk Class',
                77: 'Inform Risk Index',
                78: 'Hazard and Exposure',
                79: 'Vulnerability',
                80: 'Lack of Coping Capacity',
                81: 'Total Population',
                82: 'Enter Population',
                83: 'Source',
                84: 'Enter Source',
                87: 'Add Admin Level',
                88: 'Are you sure you want to remove admin level',
                89: 'Admin Level',
                90: 'Add Level Name',
                91: 'Country',
                92: 'Name Property',
                93: 'NAME_ENGL',
                94: 'Pcode Property',
                95: 'NAME_PCODE',
                96: 'Parent name property',
                97: 'NAME_ENFG',
                98: 'Parent pcode property',
                99: 'NAME_PPCODE',
                100: 'Parent Admin Level',
                101: 'Country Code',
                102: 'NPL',
                103: 'Name',
                104: 'Nepal',
                105: 'WB Region',
                106: 'Enter WB Region',
                107: 'WB Income Region',
                108: 'Enter WB Income Region',
                109: 'OCHA Region',
                110: 'Enter OCHA Region',
                111: 'ECHO Region',
                112: 'Enter ECHO Region',
                113: 'UN Geographical Region',
                114: 'Enter UN Geographical Region',
                115: 'UN Geographical Sub Region',
                116: 'Enter UN Geographical Sub Region',
                117: 'There are no countries.',
                118: 'Select a country to view its detail.',
                119: 'Selected county is not found.',
                120: 'Level',
                121: 'Admin Level Name',
                123: 'Admin Levels',
                124: 'GEO Shape File :',
                125: 'Load GEO Shape File',
                129: 'Extract lead information from url',
                130: 'Apply this value to all',
                131: 'Apply this value to all below',
                132: 'Preview Not Available',
                133: 'Are you sure you want to discard this lead?',
                135: 'Search Similar Lead',
                136: 'Edit lead',
                137: 'Remove lead',
                138: 'Add entry from this lead',
                139: 'Add subcategory',
                141: 'Are you sure you want to remove this lead? The lead along with all the associated entries will be removed.',
                150: 'First Name',
                151: 'eg: John',
                152: 'Last Name',
                153: 'eg: Doe',
                154: 'Organization',
                155: 'eg: ToggleCorp',
                158: 'Edit Profile',
                160: 'Rights',
                161: 'Joined At',
                163: 'Created At',
                164: 'Last Modified At',
                166: 'Members',
                167: 'View User Group',
                168: 'Edit User Group',
                169: 'Delete User Group',
                170: 'View Project',
                171: 'Edit Project',
                172: 'Delete Project',
                173: 'Projects',
                174: 'Add Project',
                175: 'Groups',
                176: 'Add User Group',
                178: 'eg: ACAPS',
                179: 'Create',
                180: 'Project Title',
                181: 'Enter Project Name',
                184: 'Email',
                185: 'Start Date',
                187: 'View Member',
                188: 'Revoke Admin Rights',
                189: 'Grant Admin Rights',
                190: 'Delete Member',
                191: 'Delete Lead',
                192: 'Add Member',
                193: 'Are you sure you want to delete the project',
                195: 'Revoke admin rights form',
                196: 'Grant admin rights to',
                198: 'User Group Not Found',
                199: 'User Not Found',
                200: 'Description',
                201: 'User Group',
                202: 'Activity Log',
                203: 'Profile Image Missing',
                301: 'Add',
                302: 'Search Project',
                303: 'Add New Project',
                304: 'Select a project to view its details',
                305: 'You do not have enough permissions to view / edit this project',
                316: 'Are you sure you want to',
                319: 'Are you sure you want to remove',
                323: 'Update',
                324: 'Revert',
                331: 'Enter Project Description',
                333: 'Enter Project Start Date',
                334: 'End Date',
                335: 'Enter Project End Date',
                336: 'Regions',
                337: 'Select regions',
                338: 'User Groups',
                339: 'Select user groups',
                341: 'Search Regions',
                342: 'Add Region',
                343: 'There are no regions in this project.',
                344: 'Create new region',
                345: 'Use existing regions',
                346: 'Region Title',
                347: 'eg: Nepal',
                348: 'Code',
                349: 'eg: NPL',
                350: 'ID',
                351: 'Remove Region',
                352: 'Clone & Edit',
                354: 'Are you sure you want to clone',
                357: 'Search Analysis Framework',
                358: 'Add New Analysis Framework',
                359: 'There are no analysis frameworks.',
                361: 'eg: ACAPS framework',
                362: 'Use',
                363: 'Edit',
                365: 'Are you sure you want to use ',
                366: 'If you use this analysis framework,you will recieve updates if the owner updates it',
                369: 'eg: ACAPS Category Editor',
                370: 'Search Category Editor',
                371: 'Add New Category Editor',
                372: 'There are no category editors.',
                373: 'If you use this category editor, you will recieve updates if the owner updates it.',
                374: 'After cloning and editing this category editor, you will not recieve any updates made by owner.',
                377: 'General Details',
                378: 'General Info',
                379: 'Analysis Framework',
                380: 'Category Editor',
                401: 'Category',
                402: 'Select Category',
                403: 'Add Category',
                404: 'Edit Category',
                405: 'Delete Category',
                406: 'Nothing Here',
                408: 'eg: Sector, Affected Groups, etc.',
                410: 'Ok',
                411: 'eg: Wash',
                413: 'eg: Wash stands for Water, Sanitation and Hygiene',
                414: 'Add new Sub-Category',
                415: 'Add New Word',
                416: 'Word',
                417: 'eg: people affected',
                418: 'Sub-Category Details',
                419: 'Remove',
                420: 'Number of Words:',
                421: 'No words yet',
                422: 'Add Word Manually',
                423: 'Document',
                424: 'Simplified',
                425: 'Extracted Words',
                426: 'Select From Gallery',
                427: 'Apply',
                428: 'Are you sure you want to delete category',
                429: 'Are you sure you want to delete  subcategory',
                500: 'Server Error',
                501: 'Failed connecting to server',
                502: 'NLP',
                504: 'It\'s Accurate',
                505: 'It\'s not Accurate',
                506: 'Show suggestions for :',
                508: 'Entities',
                509: 'Go to Overview',
                511: 'Go to List',
                512: 'Entry',
                513: 'Image',
                514: 'Excerpt',
                515: 'Format excerpt',
                517: 'Assisted',
                518: 'Original',
                519: 'Images',
                521: 'Select an excerpt',
                522: 'Add Entry',
                523: 'Mark current entry for removal',
                525: 'Unmark current entry for removal',
                528: 'Clear',
                530: 'Edit Entry',
                531: 'Set',
                533: 'Select geo region',
                534: 'Couldn\'t load geo filter options',
                535: 'Select locations',
                537: 'Search Excerpt',
                538: 'Created By',
                540: 'NER',
                541: 'Assited tagging feedback',
                542: 'Thank you for your feedback',
                543: 'Oops! It seems you don\'t have any entries. Please go back to the overview page to add one.',
                545: 'Locations',
                600: 'Export',
                601: 'Show Preview',
                602: 'Start Export',
                603: 'DOCX',
                604: 'PDF',
                605: 'XLXS',
                606: 'JSON',
                609: 'Entry Attributes',
                610: 'Lead Attributes',
                620: 'View all exports',
                621: 'User Exports',
                622: 'Unable to load your previous exports',
                623: 'Doc. type',
                624: 'Exported At',
                627: 'Export Type',
                628: 'Download',
                629: 'Pending',
                630: 'Error',
                631: 'Completed',
                632: 'Recent Exports',
                633: 'Go back to exports',
                634: 'Decoupled Entries',
                635: 'Note that by selecting this option, it can greatly increase the amount of time to generate the export.',
                636: 'Disaggregate data for any list values (i.e. multiple administrative areas or multiple select fields).',
                637: 'Your export has been started.\nPlease go to view all exports page for further information on export.',
                638: 'You don\'t have any matrices in your analysis framework.',
                639: 'Report Structure',
                640: 'No export options available',
                641: 'Leads',
                642: 'Couldn\'t load leads',
                643: 'Select',
                646: 'Couldn\'t load project',
                648: 'Couldn\'t load analysis framework',
                704: 'Date',
                706: 'Text or Image Excerpt',
                709: 'Geo Location',
                713: 'Geo Area',
                718: 'Matrix 1D',
                719: 'Add / edit cell',
                720: 'Add Cell',
                721: 'Edit row',
                722: 'Add row',
                723: 'Matrix 2D',
                724: 'Dimension-Y',
                726: 'Dimension-X',
                733: 'Tooltip',
                737: 'Multiselect',
                738: 'Option',
                739: 'eg: Context',
                740: 'Edit Multiselect',
                741: 'Add Option',
                742: 'Number Matrix',
                744: 'eg: Row',
                745: 'eg: Its a tooltip',
                746: 'eg: Column',
                747: 'Edit number matrix',
                748: 'Rows',
                749: 'Add Row Unit',
                750: 'Columns',
                751: 'Add Column Unit',
                752: 'Number',
                753: 'Organigram',
                754: 'Organ',
                755: 'Edit Organigram',
                757: 'Scale',
                758: 'eg: Reliable',
                759: 'Edit Scales',
                760: 'Add Scale Unit',
                763: 'eg: Overview',
                764: 'Color',
                766: 'Add Child',
                767: 'Remove Element',
                768: 'eg: 999 999',
                773: 'Edit Title',
                775: 'Options',
                777: 'Information date',
                778: 'Exit',
                779: 'Default?',
                780: 'List',
                781: 'Overview',
                782: 'Untitled dimension',
                786: 'Subdimensions',
                788: 'Add subdimension',
                789: 'Add dimension',
                792: 'Edit Matrix-2d',
                803: 'Welcome to DEEP (BETA)',
                805: 'Login with HID',
                806: 'Or',
                808: 'Password',
                809: 'Forgot Password ?',
                810: 'Do not have an account yet?',
                811: 'Register',
                812: 'Check your inbox:',
                813: 'john.doe@mail.com',
                814: 'Login',
                817: 'Go back to login',
                819: 'John',
                821: 'Doe',
                823: 'Togglecorp',
                824: 'Password should be more than four characters long.',
                825: 'Already have an account?',
                826: 'Submit',
                870: 'Error 404',
                871: 'Oops! You have come too DEEP',
                872: 'This is where the DEEP Kraken rests',
                873: 'Go to DEEP',
                875: 'Welcome to the',
                876: 'DEEP',
                877: 'Seems like you do not have any projects yet',
                878: 'To get started, create a project from your profile',
                879: 'Go to your profile',
                900: 'User Profile Edit',
                901: 'User Edit Successful',
                902: 'User Edit Failure.',
                903: 'User Edit Failure. Please check your network connection and try again',
                904: 'User Group Delete',
                905: 'User Group Successfully Deleted',
                906: 'User Group Deletion Failure',
                907: 'User Group Deletion Failure. Please check your network connection and try again',
                908: 'User Group Add',
                909: 'User Group Successfully Created',
                910: 'User Group Creation Failure',
                911: 'User Group Creation Failure. Please check your network connection and try again',
                912: 'User Project Delete',
                913: 'Project Successfully Deleted',
                914: 'Project Deletion Failure',
                915: 'Project Deletion Failure. Please check your network connection and try again',
                916: 'User Project Add',
                917: 'Project Successfully Created',
                918: 'Project Creation Failure',
                919: 'Project Creation Failure. Please check your network connection and try again',
                920: 'Add User Membership ',
                921: 'User Added Successfully ',
                922: 'Cannot add user',
                923: 'Cannot add user. Please check your network connection and try again',
                924: 'Remove User Membership',
                925: 'User Removed Successfully ',
                926: 'Cannot remove user',
                927: 'Cannot remove user. Please check your network connection and try again',
                928: 'Membership Role',
                929: 'User role successfully updated',
                930: 'User role update failure.',
                931: 'Cannot update user role. Please check your network connection and try again',
                932: 'User Group Edit',
                933: 'Name Updated Successfully',
                934: 'Edit Failure.',
                935: 'Edit Failure. Please check your network connection and try again',
                937: 'Country Delete Successful',
                938: 'Cannot delete country.',
                939: 'Cannot delete country. Please check your network connection and try again',
                940: 'Add Country',
                941: 'Country Added Successfully',
                942: 'Cannot add country.',
                943: 'Cannot add country. Please check your network connection and try again',
                944: 'Region Detail',
                945: 'Region Detail Successfully Updated',
                946: 'Cannot update region detail.',
                947: 'Cannot update region detail. Please check your network connection and try again',
                948: 'Delete Admin Level',
                949: 'Admin Level Successfully Deleted',
                950: 'Cannot delete admin level.',
                951: 'Cannot delete admin level. Please check your network connection and try again',
                953: 'Admin Level Successfully Added',
                954: 'Cannot add admin level.',
                955: 'Cannot add admin level. Please check your network connection and try again',
                956: 'Edit Admin Level',
                957: 'Admin Level Successfully Updated',
                958: 'Cannot update admin level.',
                959: 'Cannot update admin level. Please check your network connection and try again',
                960: 'Project Details',
                961: 'Project Details Successfully Updated',
                962: 'Cannot update project details.',
                963: 'Cannot update project details. Please check your network connection and try again',
                965: 'Analysis Framework Successfully Added ',
                966: 'Cannot add Analysis Framework.',
                967: 'Cannot add Analysis Framework. Please check your network connection and try again',
                968: 'Analysis Framework Form',
                969: 'Analysis Framework Form Updated',
                970: 'Cannot update Analysis Framework Form.',
                971: 'Cannot update Analysis Framework Form. Please check your network connection and try again',
                972: 'Save Lead',
                973: 'Lead Save Successful',
                974: 'Lead Save Failed.',
                975: 'Lead Save Failed. Please check your network connection and try again',
                977: 'Lead Successfully Deleted',
                978: 'Oops!! Lead File Not Found',
                981: 'Analysis Framework was updated in server.',
                982: 'Your copy was overridden by server\'s copy',
                983: 'Successfully saved the framework',
                984: 'Category editor was updated in server.',
                985: 'Invalid drop source',
                986: 'Drag and Drop are only valid from Extracted Words.',
                987: 'Some entries were updated in server.',
                988: 'Save Entry',
                989: 'Entries Successfully Saved',
                990: 'Entry Save Failed.',
                992: 'Discard Lead',
                993: 'Lead Successfully Discarded',
                994: 'Discard Leads',
                995: 'Leads Successfully Discarded',
                1200: 'User',
                1206: 'Search Gallery Files',
                1209: 'Loading File',
                1210: 'Open Dropbox chooser',
                1211: 'Open Google chooser',
                1214: 'Map Not Available',
                1217: 'Anon',
                1219: 'Select Event',
                1220: 'Admin Panel',
                1221: 'Logout',
                1222: 'Locating the required gigapixels to render ...',
                1223: 'Programming the flux capacitor ...',
                1224: 'Shovelling coal into the server ...',
                1225: 'Spinning up the hamster ...',
                1226: 'Checking the gravitational constant in your locale ...',
                1227: 'The server is powered by a lemon and two electrodes ...',
                1228: 'Don\'t think of purple hippos ...',
                1229: 'Dividing eternity by zero, please be patient...',
                1230: 'Photographing cats... Attaching signs... MEME complete ...',
                1231: 'Nobody exists on purpose, nobody belongs anywhere ...',
                1232: 'Swapping time and space...',
                1233: 'Greetings Earthling! ...',
                1234: 'I am Mr. Meeseeks! Look at me ...',
                1235: 'Oh, yeaah! You gotta get schwifty. ...',
                1236: 'Shhhh! The Kraken is sleeping ...',
                1237: 'BETA',
                1300: 'Are you sure you want to leave? You may lose your unsaved changes.',
                1301: 'Oops! File Not Found',
                2000: 'Browser Extension',
                2001: 'Your extension has been successfully set up.',
                2002: 'An error occured while setting up the extension. Please make sure you have installed and enabled the extension.',
                2003: 'Do you want to apply this value to all leads?',
                2004: 'Do you want to apply this value to all leads below?',
                2005: 'Do you want to apply this value to all entries?',
                2006: 'Do you want to apply this value to all entries below?',
                5551: 'Selected',
                5552: 'All',
                5553: 'Filtered',
                5555: 'Discard',
                5556: 'Invalid file(s) selected.',
                5557: 'File Selection',
                5558: 'Password Reset',
                5559: 'Home',
                5560: 'Dashboard',
                5561: 'Leads Visualization',
                5562: 'Assessment Registry',
                5564: 'Edit Entries',
                5566: 'User Profile',
                5567: 'Country Panel',
                5568: 'Project Panel',
                5569: 'Weekly Snapshot',
                5570: 'Api Docs',
                5571: '404',
                5572: 'String Management',
                6000: 'Do you want to remove this widget?',
                7000: 'Highlights',
                7001: 'Metadata',
                7002: 'Methodology',
                7003: 'Summary',
                7004: 'Score',
                7005: 'Crisis Type',
                7006: 'Crisis Start Date',
                7007: 'Preparedness',
                7008: 'External Support',
                7009: 'Coordination',
                7010: 'Cost',
                7011: 'Stakeholders',
                7012: 'Lead',
                7013: 'Partners',
                7014: 'Government',
                7015: 'Donors',
                7016: 'Publication Date',
                7017: 'Frequency',
                7018: 'Structure Section',
                7019: 'Drag and Drop data here or use KOBO link',
                7020: 'Drag and Drop Questionnaire here or select page to cut',
                7021: 'Drag and Drop other documents here',
                7022: 'Background',
                7023: 'Collection Technique',
                7024: 'Sampling',
                7025: 'Approach',
                7026: 'Size',
                7027: 'Proximity',
                7028: 'Unit Of Analysis',
                7029: 'Disaggregation',
                7030: 'Questions',
                7031: 'Topic Assessed',
                7032: 'Affected Groups',
                7033: 'Drag and Drop data collection techniques here',
                7034: 'Drag and Drop Sampling (site and respondent selection) here',
                7035: 'Drag and Drop limitations here',
                7036: 'Response Schema',
                7037: 'Request Schema',
                7038: 'Loading Api',
                7039: 'Subsectors',
            },
            views: {
                af: {
                    analysisFramework: 379,
                    headerList: 780,
                    headerOverview: 781,
                    gotoListButtonLabel: 511,
                    saveButtonLabel: 25,
                    cancelButtonLabel: 61,
                    gotoOverviewButtonLabel: 509,
                    dateWidgetLabel: 704,
                    excerptWidgetLabel: 514,
                    textOrImageExcerptWidgetLabel: 706,
                    geoWidgetLabel: 709,
                    geoAreaButtonLabel: 713,
                    matrix1DWidgetLabel: 718,
                    matrix1DModalTitle: 719,
                    addCellButtonLabel: 720,
                    editRowModalTitle: 721,
                    addRowButtonLabel: 722,
                    titlePlaceholderOverview: 763,
                    matrix2DWidgetLabel: 723,
                    dimensionXLabel: 726,
                    dimensionYLabel: 724,
                    untiledDimensionTitle: 782,
                    tooltipTitle: 733,
                    multiselectWidgetLabel: 737,
                    optionLabel: 738,
                    optionPlaceholder: 739,
                    editMultiselectModalTitle: 740,
                    addOptionButtonLabel: 741,
                    numberMatrixWidgetLabel: 742,
                    titleLabel: 13,
                    titlePlaceholderRow: 744,
                    tooltipPlaceholder: 745,
                    titlePlaceholderColumn: 746,
                    editNumberMatrixModalTitle: 747,
                    rowsLabel: 748,
                    addRowUnitButtonLabel: 749,
                    columnsLabel: 750,
                    addColumnUnitButtonLabel: 751,
                    numberWidgetLabel: 752,
                    organigramWidgetLabel: 753,
                    organPlaceholder: 754,
                    editOrganigramModaltitle: 755,
                    applyButtonLabel: 427,
                    scaleWidgetLabel: 757,
                    titlePlaceholderScale: 758,
                    editScaleModalTitle: 759,
                    addscaleUnitButtonLabel: 760,
                    altEntryLabel: 512,
                    colorLabel: 764,
                    addChildButtonTitle: 766,
                    removeElementButtonTitle: 767,
                    numberPlaceholder: 768,
                    editTitleModalHeader: 773,
                    widgetTitlePlaceholder: 13,
                    optionsHeader: 775,
                    informationDateCheckboxLabel: 777,
                    exitButtonLabel: 778,
                    defaultButtonLabel: 779,
                    title: 13,
                    tooltip: 733,
                    color: 764,
                    subdimensions: 786,
                    addSubdimensionButtonTitle: 788,
                    addDimensionButtonTitle: 789,
                    saveButtonTitle: 25,
                    cancelButtonTitle: 61,
                    editModalTitle: 792,
                    empty: 406,
                    confirmDeletewWidget: 6000,
                    subsectorsLabel: 7039,
                    formatExcerpt: 515,
                },
                api: {
                    loadingLabel: 7038,
                    responseSchemaLabel: 7036,
                    requestSchemaLabel: 7037,
                },
                ary: {
                    highlightsTabLabel: 7000,
                    metadataTabLabel: 7001,
                    methodologyTabLabel: 7002,
                    entriesTabLabel: 15,
                    summaryTabLabel: 7003,
                    scoreTabLabel: 7004,
                    crisisTypeLabel: 7005,
                    crisisStartDateLabel: 7006,
                    preparednessLabel: 7007,
                    externalSupportLabel: 7008,
                    coordinationLabel: 7009,
                    costLabel: 7010,
                    stakeholdersLabel: 7011,
                    leadLabel: 7012,
                    partnersLabel: 7013,
                    governmentLabel: 7014,
                    donorsLabel: 7015,
                    startDateLabel: 185,
                    endDateLabel: 334,
                    publicationDateLabel: 7016,
                    statusLabel: 8,
                    frequencyLabel: 7017,
                    confidentialityLabel: 7,
                    structureSectionLabel: 7018,
                    dragKoboLabel: 7019,
                    dragQuestionLabel: 7020,
                    dragDocumentLabel: 7021,
                    backgroundLabel: 7022,
                    datesLabel: 7023,
                    collectionTechniqueLabel: 7024,
                    samplingLabel: 7025,
                    approachLabel: 7026,
                    sizeLabel: 7027,
                    proximityLabel: 7028,
                    unitOfAnalysisLabel: 7029,
                    disaggregationLabel: 7030,
                    questionsLabel: 7030,
                    topicAssessedLabel: 7031,
                    affectedGroupsLabel: 7032,
                    locationLabel: 545,
                    dragDataCollectionlabel: 7034,
                    dragSamplingLabel: 7035,
                    dragLimitationsLabel: 7035,
                },
                ce: {
                    saveCeButtonLabel: 25,
                    headerCategoryLabel: 401,
                    selectCategoryPlaceholder: 402,
                    addCategoryTooltip: 403,
                    editCategoryTooltip: 404,
                    deleteCategoryTooltip: 405,
                    nothingHereText: 406,
                    addCategoryTitleLabel: 13,
                    addCategoryTitlePlaceholder: 408,
                    modalCancel: 61,
                    modalOk: 410,
                    addNewSubCategoryModalTitle: 414,
                    addSubCategoryTitleLabel: 13,
                    addSubCategoryTitlePlaceholder: 411,
                    addSubCategoryDescriptionLabel: 200,
                    addSubCategoryDescriptionPlaceholder: 413,
                    addNewWordModalTitle: 415,
                    addNewWordLabel: 416,
                    addNewWordPlaceholder: 417,
                    subCategoryDetailsText: 418,
                    removeCategoryButtonLabel: 419,
                    subCategoryTitleLabel: 13,
                    subCategoryTitlePlaceholder: 408,
                    subCategoryDescriptionLabel: 200,
                    subCategoryDescriptionPlaceholder: 413,
                    numberOfWordsLabel: 420,
                    noWordsText: 421,
                    addWordManuallyButtonLabel: 422,
                    documentTabLabel: 423,
                    simplifiedTabLabel: 424,
                    ngramsTabLabel: 425,
                    selectFromGalleryButtonLabel: 426,
                    applyButtonLabel: 427,
                    titleLabel: 13,
                    confirmTextDeleteCategory: 428,
                    confirmTextDeleteSubCategory: 429,
                    exitButtonLabel: 778,
                    addSubcategory: 139,
                },
                common: {
                    altUser: 1200,
                    tableHeaderSelect: 643,
                    tableHeaderType: 21,
                    tableHeaderName: 103,
                    tableHeaderDateCreated: 2,
                    searchGalleryLabel: 9,
                    searchGalleryPlaceholder: 1206,
                    cancelButtonLabel: 61,
                    addButtonLabel: 301,
                    loadingFileLabel: 1209,
                    openDropboxChooserText: 1210,
                    openGoogleChooserText: 1211,
                    serverErrorText: 500,
                    connectionFailureText: 501,
                    mapNotAvailable: 1214,
                    previewNotAvailable: 132,
                    anonymousLabel: 1217,
                    deepLabel: 876,
                    selectEventPlaceholder: 1219,
                    adminPanelLabel: 1220,
                    logoutLabel: 1221,
                    loadingMessages1: 1222,
                    loadingMessages2: 1223,
                    loadingMessages3: 1224,
                    loadingMessages4: 1225,
                    loadingMessages5: 1226,
                    loadingMessages6: 1227,
                    loadingMessages7: 1228,
                    loadingMessages8: 1229,
                    loadingMessages9: 1230,
                    loadingMessages10: 1231,
                    loadingMessages11: 1232,
                    loadingMessages12: 1233,
                    loadingMessages13: 1234,
                    loadingMessages14: 1235,
                    loadingMessages15: 1236,
                    betaLabel: 1237,
                    youHaveUnsavedChanges: 1300,
                    deepFileNotFound: 1301,
                },
                countries: {
                    countriesLabel: 51,
                    searchCountryPlaceholer: 52,
                    addCountryButtonLabel: 301,
                    deleteCountryButtonLabel: 54,
                    deleteCountryConfirm: 55,
                    generalTabLabel: 56,
                    keyFiguesTabLabel: 57,
                    populationTabLabel: 58,
                    seasonalTabLabel: 59,
                    mediaTabLabel: 60,
                    cancelButtonLabel: 61,
                    saveChangesButtonLabel: 62,
                    saveButtonLabel: 25,
                    humanDevelopmentIndexLabel: 63,
                    underFiveMortalityLabel: 64,
                    uprootedPeopleLabel: 65,
                    informScoreLabel: 66,
                    indexLabel: 67,
                    geoRankLabel: 68,
                    geoScoreLabel: 69,
                    rankLabel: 70,
                    u5mLabel: 71,
                    numberOfRefugeesLabel: 72,
                    percentageUprootedPeopleLabel: 73,
                    numberIdpLabel: 74,
                    numberReturnedRefugeesLabel: 75,
                    riskClassLabel: 76,
                    informRiskIndexLabel: 77,
                    hazardAndExposureLabel: 78,
                    vulnerabilityLabel: 79,
                    lackOfCopingCapacityLabel: 80,
                    totalPopulationLabel: 81,
                    totalPopulationPlaceholder: 82,
                    sourceLabel: 83,
                    sourcePlaceholder: 84,
                    addAdminLevelButtonLabel: 87,
                    removeAdminLevelConfirm: 88,
                    adminLevelLabel: 89,
                    adminLevelPlaceholder: 89,
                    adminLevelNameLabel: 90,
                    adminLevelNamePlaceholder: 91,
                    namePropertyLabel: 92,
                    namePropertyPlaceholder: 93,
                    pcodePropertyLabel: 94,
                    pcodePropertyPlaceholder: 95,
                    parentNamePropLabel: 96,
                    parentNamePropPlaceholder: 97,
                    parentCodePropLabel: 98,
                    parentCodePropPlaceholder: 99,
                    parentAdminLevelLabel: 100,
                    parentAdminLevelPlaceholder: 99,
                    countryCodeLabel: 101,
                    countryCodePlaceholder: 102,
                    countryNameLabel: 103,
                    countryNamePlaceholder: 104,
                    wbRegionLabel: 105,
                    wbRegionPlaceholer: 106,
                    wbIncomeRegionLabel: 107,
                    wbIncomeRegionPlaceholder: 108,
                    ochaRegionLabel: 109,
                    ochaRegionPlaceholder: 110,
                    echoRegionLabel: 111,
                    echoRegionPlaceholder: 112,
                    unGeoRegionLabel: 113,
                    unGeoRegionPlaceholer: 114,
                    unGeoSubregionLabel: 115,
                    unGeoSubregionPlaceholer: 116,
                    noCountriesText: 117,
                    selectCountryText: 118,
                    countryNotFoundText: 119,
                    levelLabel: 120,
                    adminLevelNameText: 121,
                    actionsLabel: 16,
                    adminLevelsHeader: 123,
                    editAdminLevelModalTitle: 956,
                    geoShapeFile: 124,
                    loadGeoShapeFile: 125,
                    regionGeneralInfoLabel: 378,
                    addRegionButtonLabel: 301,
                },
                entry: {
                    serverErrorText: 500,
                    connectionFailureText: 501,
                    sourceNLP: 502,
                    sourceCE: 380,
                    accurateTextTitle: 504,
                    notAccurateTextTitle: 505,
                    showSuggestionText: 506,
                    addEntryButtonLabel: 301,
                    nlpLabel: 502,
                    entitiesLabel: 508,
                    ceLabel: 380,
                    gotoOverviewButtonLabel: 509,
                    saveButtonLabel: 25,
                    gotoListButtonLabel: 511,
                    altLabel: 512,
                    previewNotAvailableText: 132,
                    simplifiedTabLabel: 424,
                    assistedTabLabel: 517,
                    originalTabLabel: 518,
                    imagesTabLabel: 519,
                    entriesTabLabel: 15,
                    selectExcerptPlaceholder: 521,
                    addEntryButtonTitle: 522,
                    removeEntryButtonTitle: 523,
                    undoRemoveEntryButtonTitle: 525,
                    applyFilterButtonLabel: 427,
                    clearFilterButtonLabel: 528,
                    editEntryLinkTitle: 363,
                    editEntryButtonLabel: 530,
                    setGeoSelectionButtonLabel: 531,
                    cancelGeoSelectionButtonLabel: 61,
                    regionSelectPlaceholder: 533,
                    geoOptionsFatalMessage: 534,
                    locationSelectPlaceholder: 535,
                    searchFilterLabel: 9,
                    searchFilterPlaceholder: 537,
                    createdByFilterLabel: 538,
                    createdAtFilterLabel: 163,
                    sourceNER: 540,
                    assitedTaggingFeedbackTitle: 541,
                    assitedTaggingFeedbackMessage: 542,
                    noEntryFound: 543,
                    regionSelectTitle: 336,
                    locationSelectTitle: 545,
                    applyAllButtonTitle: 130,
                    applyAllBelowButtonTitle: 131,
                    applyToAll: 2005,
                    applyToAllBelow: 2006,
                },
                export: {
                    headerExport: 600,
                    showPreviewButtonLabel: 601,
                    startExportButtonLabel: 602,
                    viewAllExportsButtonLabel: 620,
                    docxLabel: 603,
                    pdfLabel: 604,
                    xlxsLabel: 605,
                    jsonLabel: 606,
                    entryAttributesLabel: 609,
                    leadAttributesLabel: 610,
                    createdAtLabel: 163,
                    previewNotAvailableLabel: 132,
                    serverErrorText: 500,
                    connectionFailureText: 501,
                    userExportsTitle: 621,
                    userExportsFataMessage: 622,
                    documentTypeHeaderLabel: 623,
                    exportedAtHeaderLabel: 624,
                    exportTitleHeaderLabel: 13,
                    statusHeaderLabel: 8,
                    exportTypeHeaderLabel: 627,
                    exportDownloadHeaderLabel: 628,
                    pendingStatusLabel: 629,
                    errorStatusLabel: 630,
                    completedStatusLabel: 631,
                    userExportsHeader: 632,
                    goBackToExportLabel: 633,
                    decoupledEntriesLabel: 634,
                    decoupledEntriesTitle: 635,
                    decoupledEntriesTitle2: 636,
                    exportStartedNotifyMessage: 637,
                    noMatrixAfText: 638,
                    noOptionsAvailable: 640,
                    reportStructureLabel: 639,
                    leadsLabel: 641,
                    cantLoadLeads: 642,
                    selectLabel: 643,
                    titleLabel: 13,
                    projectLabel: 31,
                    cantLoadProject: 646,
                    afLabel: 379,
                    cantLoadAf: 648,
                },
                fourHundredFour: {
                    errorFourHundredFour: 870,
                    message1: 871,
                    message2: 872,
                    goToDeep: 873,
                },
                homescreen: {
                    welcomeText: 875,
                    deepLabel: 876,
                    message1: 877,
                    message2: 878,
                    goToProfile: 879,
                },
                leads: {
                    filterDateCreated: 2,
                    filterDatePublished: 3,
                    filterConfidentiality: 7,
                    filterStatus: 8,
                    filterApplyFilter: 10,
                    filterClearFilter: 11,
                    filterClearSimilarFilter: 47,
                    filterSourceType: 21,
                    filterPublisher: 5,
                    placeholderAnybody: 17,
                    placeholderAnytime: 18,
                    placeholderAny: 14,
                    placeholderSearch: 9,
                    tableHeaderOwner: 1,
                    tableHeaderDateCreated: 2,
                    tableHeaderDatePublished: 3,
                    tableHeaderConfidentiality: 7,
                    tableHeaderPublisher: 5,
                    tableHeaderNoOfEntries: 15,
                    tableHeaderStatus: 8,
                    tableHeaderActions: 16,
                    addSourcesButtonLabel: 12,
                    previousButtonLabel: 22,
                    nextButtonLabel: 23,
                    saveCurrentButtonTitle: 5551,
                    saveAllButtonTitle: 5552,
                    saveAllFilteredButtonTitle: 5553,
                    removeCurrentButtonTitle: 5551,
                    removeAllButtonTitle: 5552,
                    removeAllFilteredButtonTitle: 5553,
                    removeButtonTitle: 5555,
                    cannotPreviewUrl: 28,
                    invalidUrl: 30,
                    addSourceFromLabel: 34,
                    googleDriveLabel: 35,
                    dropboxLabel: 36,
                    localDiskLabel: 37,
                    textLabel: 20,
                    projectLabel: 31,
                    titleLabel: 13,
                    publisherLabel: 5,
                    confidentialityLabel: 7,
                    assigneeLabel: 6,
                    datePublishedLabel: 3,
                    urlLabel: 32,
                    websiteLabel: 33,
                    selectInputPlaceholderLabel: 38,
                    projectPlaceholderLabel: 39,
                    titlePlaceHolderLabel: 40,
                    urlPlaceholderLabel: 41,
                    publisherPlaceHolderLabel: 43,
                    datePublishedPlaceholderLabel: 44,
                    textareaPlaceholderLabel: 45,
                    sourcePreview: 48,
                    gatheringWebsiteInfoLabel: 49,
                    applyAllButtonTitle: 130,
                    applyAllBelowButtonTitle: 131,
                    previewNotAvailable: 132,
                    deleteLeadConfirmText: 133,
                    searchSimilarLeadButtonTitle: 135,
                    editLeadButtonTitle: 136,
                    removeLeadLeadButtonTitle: 137,
                    addEntryFromLeadButtonTitle: 138,
                    leadDeleteConfirmText: 141,
                    leadDeleteSuccess: 977,
                    leadFileNotFound: 978,
                    extractLead: 129,
                    applyToAll: 2003,
                    applyToAllBelow: 2004,
                    leadDelete: 191,
                },
                login: {
                    welcomeToText: 803,
                    logInWIthHid: 805,
                    orText: 806,
                    emailLabel: 184,
                    passwordLabel: 808,
                    forgotPasswordText: 809,
                    noAccountYetText: 810,
                    checkInboxText: 812,
                    emailPlaceholder: 813,
                    loginLabel: 814,
                    registerLabel: 811,
                    goBackToLoginText: 817,
                    firstNameLabel: 150,
                    firstNamePlaceholder: 819,
                    lastNameLabel: 152,
                    lastNamePlaceholder: 821,
                    organizationLabel: 154,
                    organizationPlaceholder: 823,
                    passwordHint: 824,
                    alreadyHaveAccountText: 825,
                    submitForgetPassword: 826,
                },
                notification: {
                    userProfileEdit: 900,
                    userEditSuccess: 901,
                    userEditFailure: 902,
                    userEditFatal: 903,
                    userGroupDelete: 904,
                    userGroupDeleteSuccess: 905,
                    userGroupDeleteFailure: 906,
                    userGroupDeleteFatal: 907,
                    userGroupCreate: 908,
                    userGroupCreateSuccess: 909,
                    userGroupCreateFailure: 910,
                    userGroupCreateFatal: 911,
                    userProjectDelete: 912,
                    userProjectDeleteSuccess: 913,
                    userProjectDeleteFailure: 914,
                    userProjectDeleteFatal: 915,
                    userProjectCreate: 916,
                    userProjectCreateSuccess: 917,
                    userProjectCreateFailure: 918,
                    userProjectCreateFatal: 919,
                    userMembershipCreate: 920,
                    userMembershipCreateSuccess: 921,
                    userMembershipCreateFailure: 922,
                    userMembershipCreateFatal: 923,
                    userMembershipDelete: 924,
                    userMembershipDeleteSuccess: 925,
                    userMembershipDeleteFailure: 926,
                    userMembershipDeleteFatal: 927,
                    userMembershipRole: 928,
                    userMembershipRoleSuccess: 929,
                    userMembershipRoleFailure: 930,
                    userMembershipRoleFatal: 931,
                    userGroupEdit: 932,
                    userGroupEditSuccess: 933,
                    userGroupEditFailure: 934,
                    userGroupEditFatal: 935,
                    countryDelete: 54,
                    countryDeleteSuccess: 937,
                    countryDeleteFailure: 938,
                    countryDeleteFatal: 939,
                    countryCreate: 940,
                    countryCreateSuccess: 941,
                    countryCreateFailure: 942,
                    countryCreateFatal: 943,
                    regionDetail: 944,
                    regionDetailSuccess: 945,
                    regionDetailFailure: 946,
                    regionDetailFatal: 947,
                    adminLevelDelete: 948,
                    adminLevelDeleteSuccess: 949,
                    adminLevelDeleteFailure: 950,
                    adminLevelDeleteFatal: 951,
                    adminLevelCreate: 87,
                    adminLevelCreateSuccess: 953,
                    adminLevelCreateFailure: 954,
                    adminLevelCreateFatal: 955,
                    adminLevelEdit: 956,
                    adminLevelEditSuccess: 957,
                    adminLevelEditFailure: 958,
                    adminLevelEditFatal: 959,
                    projectDetails: 960,
                    projectDetailsSuccess: 961,
                    projectDetailsFailure: 962,
                    projectDetailsFatal: 963,
                    afCreate: 379,
                    afCreateSuccess: 965,
                    afCreateFailure: 966,
                    afCreateFatal: 967,
                    afFormEdit: 968,
                    afFormEditSuccess: 969,
                    afFormEditFailure: 970,
                    afFormEditFatal: 971,
                    leadSave: 972,
                    leadSaveSuccess: 973,
                    leadSaveFailure: 974,
                    leadSaveFatal: 975,
                    leadDiscard: 992,
                    leadDiscardSuccess: 993,
                    leadsDiscard: 994,
                    leadsDiscardSuccess: 995,
                    afTitle: 379,
                    afUpdate: 981,
                    afUpdateOverridden: 982,
                    afSaveSuccess: 983,
                    ceUpdate: 984,
                    ceUpdateOverridden: 982,
                    invalidDropSource: 985,
                    validDropAlert: 986,
                    entryUpdate: 987,
                    entryUpdateOverridden: 982,
                    browserExtensionSuccessTitle: 2000,
                    browserExtensionSuccessMessage: 2001,
                    browserExtensionFailureTitle: 2000,
                    browserExtensionFailureMessage: 2002,
                    entrySave: 988,
                    entrySaveSuccess: 989,
                    entrySaveFailure: 990,
                    entrySaveFatal: 975,
                    invalidFileSelection: 5556,
                    fileSelection: 5557,
                },
                pageTitle: {
                    login: 814,
                    register: 811,
                    passwordReset: 5558,

                    homeScreen: 5559,
                    dashboard: 5560,

                    leads: 641,
                    leadsViz: 5561,
                    addLeads: 12,
                    entries: 15,
                    ary: 5562,
                    export: 600,

                    editEntries: 5564,

                    userProfile: 5566,
                    userGroup: 201,
                    adminPanel: 1220,
                    countries: 5567,
                    projects: 5568,

                    analysisFramework: 379,

                    categoryEditor: 380,

                    weeklySnapshot: 5569,

                    apiDocs: 5570,
                    userExports: 621,

                    fourHundredFour: 5571,

                    browserExtension: 2000,
                    stringManagement: 5572,
                },
                project: {
                    headerProjects: 173,
                    addProjectButtonLabel: 301,
                    searchProjectPlaceholder: 302,
                    addProjectModalTitle: 303,
                    noProjectText: 304,
                    forbiddenText: 305,
                    tableHeaderName: 103,
                    tableHeaderEmail: 184,
                    tableHeaderRights: 160,
                    tableHeaderJoinedAt: 161,
                    tableHeaderActions: 16,
                    viewMemberLinkTitle: 187,
                    deleteMemberLinkTitle: 190,
                    revokeAdminRightsTitle: 188,
                    grantAdminRightsTitle: 189,
                    confirmText: 316,
                    confirmTextRevokeAdmin: 195,
                    confirmTextGrantAdmin: 196,
                    confirmTextRemove: 319,
                    headerMembers: 166,
                    addMemberButtonLabel: 192,
                    modalCancel: 61,
                    modalUpdate: 323,
                    modalRevert: 324,
                    modalSave: 25,
                    modalAdd: 301,
                    projectNameLabel: 103,
                    projectNamePlaceholder: 39,
                    projectDescriptionLabel: 200,
                    projectDescriptionPlaceholder: 331,
                    projectStartDateLabel: 185,
                    projectStartDatePlaceholder: 333,
                    projectEndDateLabel: 334,
                    projectEndDatePlaceholder: 335,
                    projectRegionLabel: 336,
                    projectRegionPlaceholder: 337,
                    projectUserGroupLabel: 338,
                    projectUserGroupPlaceholder: 339,
                    addRegionButtonLabel: 301,
                    searchRegionPlaceholder: 341,
                    addRegionModalTitle: 342,
                    noRegionText: 343,
                    createNewRegionText: 344,
                    useExistingRegionText: 345,
                    addRegionTitleLabel: 346,
                    addRegionTitlePlaceholder: 347,
                    addRegionCodeLabel: 348,
                    addRegionCodePlaceholder: 349,
                    tableHeaderId: 350,
                    removeRegionButtonLabel: 351,
                    cloneEditButtonLabel: 352,
                    confirmRemoveText: 319,
                    confirmCloneText: 354,
                    addAfButtonLabel: 301,
                    searchAfPlaceholder: 357,
                    addAfModalTitle: 358,
                    noAfText: 359,
                    addAfTitleLabel: 13,
                    addAfTitlePlaceholder: 361,
                    useAfButtonLabel: 362,
                    editAfButtonLabel: 363,
                    cloneEditAfButtonLabel: 352,
                    confirmUseAf: 365,
                    confirmUseAfText: 366,
                    confirmCloneAf: 354,
                    addCeTitleLabel: 13,
                    addCeTitlePlaceholder: 369,
                    useCeButtonLabel: 362,
                    editCeButtonLabel: 363,
                    cloneEditCeButtonLabel: 352,
                    addCeButtonLabel: 301,
                    searchCePlaceholder: 370,
                    addCeModalTitle: 371,
                    noCeText: 372,
                    confirmUseCe: 365,
                    confirmUseCeText: 373,
                    confirmCloneCe: 354,
                    confirmCloneCeText: 374,
                    generalDetailsLabel: 377,
                    regionsLabel: 336,
                    analysisFrameworkLabel: 379,
                    categoryEditorLabel: 380,
                },
                user: {
                    firstNameLabel: 150,
                    firstNamePlaceholder: 151,
                    lastNameLabel: 152,
                    lastNamePlaceholder: 153,
                    organizationLabel: 154,
                    organizationPlaceholder: 155,
                    modalSave: 25,
                    modalCancel: 61,
                    modalCreate: 179,
                    editProfileModalHeader: 158,
                    tableHeaderTitle: 13,
                    tableHeaderRights: 160,
                    tableHeaderJoinedAt: 161,
                    tableHeaderActions: 16,
                    tableHeaderCreatedAt: 163,
                    tableHeaderLastModifiedAt: 164,
                    tableHeaderStatus: 8,
                    tableHeaderMembers: 166,
                    tableHeaderName: 103,
                    tableHeaderEmail: 184,
                    tableHeaderStartDate: 185,
                    viewUsergroupLinkTitle: 167,
                    editUsergroupLinkTitle: 168,
                    deleteUsergroupLinkTitle: 169,
                    viewProjectLinkTitle: 170,
                    editProjectLinkTitle: 171,
                    deleteProjectLinkTitle: 172,
                    headerProjects: 173,
                    addProjectButtonLabel: 174,
                    headerGroups: 175,
                    addUserGroupButtonLabel: 176,
                    addUserGroupModalLabel: 13,
                    addUserGroupModalPlaceholder: 178,
                    addProjectModalLabel: 180,
                    addProjectModalPlaceholder: 181,
                    userGroupEditModalLabel: 168,
                    userGroupModalDescriptionLabel: 200,
                    viewMemberLinkTitle: 187,
                    revokeAdminLinkTitle: 188,
                    grantAdminLinkTitle: 189,
                    deleteMemberLinkTitle: 190,
                    placeholderSearch: 9,
                    addMemberButtonLabel: 192,
                    confirmTextDeleteProject: 193,
                    confirmTextRevokeAdmin: 195,
                    confirmTextGrantAdmin: 196,
                    userGroupNotFound: 198,
                    userNotFound: 199,
                    userGroupTitle: 201,
                    userGroupActivtyLogTitle: 202,
                    userImageNotFound: 203,
                },
            },
        },
    },
};
export default initialLangState;
