const iconNames = {
    add: 'ion-plus',
    substract: 'ion-ios-minus-empty',
    applyAll: 'ion-ios-world',
    applyAllBelow: 'ion-android-arrow-dropdown-circle',
    apps: 'ion-android-apps',
    check: 'ion-checkmark',
    checkCircle: 'ion-checkmark-circled',
    chevronDown: 'ion-chevron-down',
    chevronLeft: 'ion-chevron-left',
    chevronRight: 'ion-chevron-right',
    chevronUp: 'ion-chevron-up',
    clipboard: 'ion-clipboard',
    close: 'ion-close',
    code: 'ion-code',
    codeWorking: 'ion-code-working',
    delete: 'ion-android-delete',
    refresh: 'ion-android-refresh',

    documentText: 'ion-document',

    json: 'ion-android-document',
    xml: 'ion-android-document',
    csv: 'ion-android-document',

    docx: 'ion-document-text',
    rtf: 'ion-document-text',
    otf: 'ion-document-text',
    msword: 'ion-document-text',

    pdf: 'ion-document-text',

    pptx: 'ion-document-text',
    ppt: 'ion-document-text',

    xls: 'ion-document-text',
    xlxs: 'ion-document-text',

    png: 'ion-image',
    jpg: 'ion-image',
    jpeg: 'ion-image',
    fig: 'ion-image',


    dropbox: 'ion-social-dropbox',
    edit: 'ion-edit',
    error: 'ion-android-alert',
    forward: 'ion-forward',
    globe: 'ion-android-globe',
    googleDrive: 'ion-social-googleplus-outline',
    hamburger: 'ion-android-menu',
    help: 'ion-help-circled',
    link: 'ion-link',
    list: 'ion-ios-list-outline',
    loading: 'ion-load-c',
    locked: 'ion-locked',
    logout: 'ion-log-out',
    openLink: 'ion-android-open',
    overflowHorizontal: 'ion-android-more-horizontal',
    person: 'ion-android-person',
    remove: 'ion-android-remove',
    removeCircle: 'ion-android-remove-circle',
    search: 'ion-search',
    text: 'ion-document',
    upload: 'ion-android-upload',
    user: 'ion-android-contact',
    warning: 'ion-alert-circled',
    wrench: 'ion-wrench',
};

export default iconNames;
